### ISSUE TITLE
OCSP Responder request logs

### ISSUE THREAD

**Issue by rolandshoemaker** [cloudflare/cfssl#1004]
(@cbroglie I think you're the current lead maintainer, so tagging you for thoughts on this)

At LE we'd like to add OCSP request logs to our OCSP responder for debugging purposes. Given we use `cfssl/ocsp.Responder` we only actually get information about the OCSP request itself, rather than the HTTP request. Instead of double parsing the OCSP request in a top level mux hack I'd rather the logging happen at the `cfssl/ocsp` level.

This is slightly complicated for us though as we don't want to _always_ collect this request information as our privacy policy indicates we will only ever collect request information for OCSP requests (i.e. IP, UA, etc) for debugging purposes. This means it'd need to either be enabled by logging at a low syslog level (presumably `LOG_DEBUG`) or by explicitly enabling it as a bool in the `Responder` constructor. Do you have strong opinions on which way you'd prefer this to be done from the CF perspective? I'd lean towards having an explicit bool as it'd be harder to accidentally enable, but either would work for us.

**Comment by cbroglie** [comment]
I think I prefer the simplicity of just logging at the debug level, but would not strongly object to a separate configuration bool.

**Comment by rolandshoemaker** [comment]
After thinking about this a bit more I think logging at debug will work just fine for our purposes. I'll whip out a PR for this today.
