### ISSUE TITLE
Your wiki is currently editable by everyone

### ISSUE THREAD

**Issue by born4new** [cloudflare/cfssl#1011]
I wanted to submit a typo fix for https://github.com/cloudflare/cfssl/wiki/Creating-a-new-CSR, and it allowed me to do the change directly (see [the history of the document](https://github.com/cloudflare/cfssl/wiki/Creating-a-new-CSR/_history)).

I doubt that this was the intended permissions on the wiki, so I am letting you know via this issue :).

**Comment by cbroglie** [comment]
Thanks for letting us know, I just changed the setting.
