### ISSUE TITLE
tag/v1.4.0: "cfssl version" outputs "dev" instead of "1.4.0"

### ISSUE THREAD

**Issue by t-hofmann** [cloudflare/cfssl#1049]
to reproduce, e. g.:
REPO_URL="github.com/cloudflare/cfssl"

go get -d -u $REPO_URL/cmd/...

cd $GOPATH/src/$REPO_URL
git checkout tags/v1.4.0
go build -o $GOPATH/bin/cfssl ./cmd/cfssl

$GOPATH/bin/cfssl version

Best,
Thomas

**Comment by cbroglie** [comment]
This is now expected when building from source, as the version is now injected at build time, see: https://github.com/cloudflare/cfssl/blob/67aae9466f3559ce0ae1c2450336ed84c0a3bb8e/.goreleaser.yml#L18

You can achieve this while building from source with:
```
go build -o $GOPATH/bin/cfssl -ldflags="-X github.com/cloudflare/cfssl/cli/version.version=$(git describe --tags --abbrev=0 | tr -d '[:alpha:]')" ./cmd/cfssl
```

**Comment by t-hofmann** [comment]
thanks that works like a charm
