### ISSUE TITLE
Provide more compatible Linux build

### ISSUE THREAD

**Issue by dsix-work** [cloudflare/cfssl#1053]
The Linux binary releases appear to be linked against glibc 2.28. To make the binaries compatible with a wider range of Linux distros it would be helpful for a statically compiled binary to be available as well.

The binaries for 1.2.0 from https://pkg.cfssl.org/ are statically compiled, so they work on all the distros tested.

Here is a comparison of the compatibility of **static**(1.2.0) and **dynamic**(1.4.0) binaries: 

| Distro | cfssl 1.2.0 | cfssl 1.4.0 |
|---------|--------------|---------------|
| Alpine (Any version) | :heavy_check_mark: | :x: |
| Debian 8/9 | :heavy_check_mark: | :x: |
| Debian 10 | :heavy_check_mark: | :heavy_check_mark: |
| EL 6/7 | :heavy_check_mark: | :x: |
| EL 8 | :heavy_check_mark: | :heavy_check_mark: |
| openSuse Leap | :heavy_check_mark: | :x: |
| openSuse Tumbleweed | :heavy_check_mark: | :heavy_check_mark: |
| Ubuntu LTS | :heavy_check_mark: | :x: |
| Ubuntu 19+ | :heavy_check_mark: | :heavy_check_mark: |

An alternate solution would be to target an older version of glibc - 2.12 would work on all the above except Alpine.

**Comment by cbroglie** [comment]
PRs are welcome, otherwise feel free to build from source as needed

**Comment by dsix-work** [comment]
Would you prefer to have both static and dynamically compiled binaries, or just static?

**Comment by cbroglie** [comment]
As long as the sizes don't become massive, I think static would be fine everywhere.

**Comment by cbroglie** [comment]
Released in 1.4.1 with the fix from @dsix-work
