### ISSUE TITLE
cfssl version prints golang's version

### ISSUE THREAD

**Issue by andpeterson** [cloudflare/cfssl#1072]
After running the following to install git go and cfssl as specified in the README
``` bash
sudo apt-get install git -y
wget -c https://dl.google.com/go/go1.13.6.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.13.6.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
source ~/.profile
go get -u github.com/cloudflare/cfssl/cmd/cfssl
sudo mv ~/go/bin/cfssl /bin/cfssl
```
and then running
``` bash
cfssl version
```
I get the output
```
Version: dev
Runtime: go1.13.6
```
which appears to be golang's version rather than the expected cfssl's version.
I'd like to note that the other cfssl commands seem to operate as cfssl typically does, including help. It just seems to be the version command that isn't working as expected.

**Comment by wbl** [comment]
The version is the version of cfssl, and since there is an untagged commit it is dev. The runtime version is the version of the go runtime. So this is working as expected, but it might be more useful if we had the tag then -dev if it was dirty.

**Comment by andpeterson** [comment]
It would be awesome then if there was a specification that 1.13.6 refers to the cfssl runtime cause it seems to be referring to go rather than cfssl in the output.

**Comment by lgarofalo** [comment]
@andpeterson Hey, my understanding that this is as expected as well, 1.13.6 is the go runtime, not a reference to a cfssl version.

Does this seem clear to you? if so I will close this as not an issue.

**Comment by andpeterson** [comment]
If it works as expected then the issue should be closed.
