### ISSUE TITLE
errors/error_test.go: TestWrap fails wish Go 1.14beta1

### ISSUE THREAD

**Issue by eclipseo** [cloudflare/cfssl#1076]
Fedora Rawhide with Go 1.14 beta1

```
github.com/cloudflare/cfssl/errors
--- FAIL: TestWrap (0.00s)
    error_test.go:244: Error message construction failed.
FAIL
```

See upstream change: https://github.com/golang/go/commit/30d7b6400860d87d810a0db3593b28dfb72879f2

**Comment by claucece** [comment]
With the current stable Go 1.14 on MacOS this also fails.
