### ISSUE TITLE
Error when go install cfssl 3rd party error

### ISSUE THREAD

**Issue by txssseal** [cloudflare/cfssl#1078]
Hey all when installing im getting this error from 3rd party dependency.  I am pretty sure I can just `make` it, but thought this would be helpful to report...

```
coltbuntu ➜  src go version
go version go1.11 linux/amd64
```

```
coltbuntu ➜  src go get -u github.com/cloudflare/cfssl/cmd/cfssl
# github.com/cloudflare/cfssl/vendor/github.com/zmap/zlint/lints
github.com/cloudflare/cfssl/vendor/github.com/zmap/zlint/lints/result.go:75:9: undefined: strings.ReplaceAll
```

**Comment by cpu** [comment]
:wave: Hi @txssseal,

> go version go1.11 linux/amd64

Your Go version is too old for the ZLint dependency. The CFSSL README says:
>  It requires Go 1.12+ to build.

**Comment by txssseal** [comment]
@cpu actually was jumping in to paste this!

https://github.com/zmap/zlint/issues/305

lol thanks for the quick reply.  issue is resolved!
