### ISSUE TITLE
Module github.com/zmap/zlint@latest found (v2.0.0+incompatible)

### ISSUE THREAD

**Issue by gavinfish** [cloudflare/cfssl#1087]
When I try to install cfssl with go get like `go get -u github.com/cloudflare/cfssl/cmd/...`, I get error message: 
```
build github.com/cloudflare/cfssl/cmd/cfssl: cannot load github.com/zmap/zlint: module github.com/zmap/zlint@latest found (v2.0.0+incompatible), but does not contain package github.com/zmap/zlint
```

go version: 1.13.8,  go env:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/drfish/.cache/go-build"
GOENV="/home/drfish/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/drfish/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/drfish/go/src/k8s.io/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build070420776=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by cpu** [comment]
> When I try to install cfssl with go get like go get -u github.com/cloudflare/cfssl/cmd/..., I get error message.

I'm not able to repro this on a clean machine with Go 1.13.9 with `go get -u github.com/cloudflare/cfssl/cmd/...` run outside of a module directory. I suspect https://github.com/cloudflare/cfssl/pull/1080 will resolve the problem for you if/when it's merged either way.

@gavinfish Are you trying to install `cfssl` to your system generally, or trying to add/update it as a dependency of `k8s.io/kubernetes`? The `GOMOD="/home/drfish/go/src/k8s.io/kubernetes/go.mod"
` output in your `go env` makes it look the latter. If you intend for the former instead you might want to try running the `go get -u` outside of the module directory fo another project.

**Comment by gavinfish** [comment]
I have solved the issue, thanks @cpu

**Comment by cpu** [comment]
Glad to hear it! Thanks for reporting back.
