### ISSUE TITLE
Add info command

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/cfssl#111]
The info API endpoint returns information about the certificate used for a CA. With the latest changes from issue #98, info can return information about remote signers. There should be a command line option to return information about remote signers.

Options to take: remote, label, profile, config

**Comment by dr107** [comment]
I'm a little unsure what this command is trying to do. What would be an example usage?

**Comment by kisom** [comment]
It would look something like

```
$ cfssl -remote ca.example.net -profile www-server 
{"success":true,"result":{"certificate":"-----BEGIN CERTIFICATE-----\n...n-----END CERTIFICATE-----"},"errors":[],"messages":[]}
```

I think it'll mostly just be a CLI interface to the `api/client.Info` function.

**Comment by dr107** [comment]
I think I get it. I'll keep poking around.

**Comment by grittygrease** [comment]
All merged.
