### ISSUE TITLE
Fix coveralls for pull requests from forks

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/cfssl#112]
Coveralls currently fails for every pull request from a remote fork. The secure token in TravisCI to authenticate to coveralls doesn't seem to be decrypted properly in this case.

**Comment by lziest** [comment]
This is completed.

**Comment by clarkduvall** [comment]
I'm having the same problem on one of my projects, how did you solve this?

**Comment by grittygrease** [comment]
@lziest This is still happening: check out the current set of pull requests.

**Comment by grittygrease** [comment]
Workaround implemented in #203
