### ISSUE TITLE
cfssljson parameter

### ISSUE THREAD

**Issue by cpbug** [cloudflare/cfssl#1127]
-bare it means？

**Comment by nickysemenza** [comment]
`cfssljson -h` explains the usage:   
```
-bare
    	the response from CFSSL is not wrapped in the API standard response
```
The standard API response is described by this struct: https://github.com/cloudflare/cfssl/blob/master/cmd/cfssljson/cfssljson.go#L37-L43

**Comment by cpbug** [comment]
thank you
