### ISSUE TITLE
Optionally overwrite CSR fields in sign

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/cfssl#114]
Currently, if you call the sign API but do not include the subject, distinguished names or CN, then these fields will be blank in the certificate. Instead, sign should take these parameters from the CSR directly if they are missing in the API call.

**Comment by dr107** [comment]
I can have a look at this.

**Comment by lziest** [comment]
This is resolved.

**Comment by grittygrease** [comment]
@lziest I think that a union of the two is not the correct behavior. What we want is to be able to override any field, but only if the field is explicitly defined in the JSON.

i.e. 
{ CN: "commonname" }
will override CN but keep SANs, names, etc.

{ CN: "commonname",
hosts: [] }
will override CN and override SANs with an empty list

{"names": [{"C": "US", "L": "San Francisco", "O": "Internet Widgets, LLC"}]
}
will keep the CN and SANs, but overwrite the names.

There are use cases in which you want to trust the CSR for the organization name, but not the domain names, such as in the Domain Validated CA case. There is no use case for appending a domain name to one extracted from a CSR.

**Comment by lziest** [comment]
This is now fixed as suggested by @grittygrease
