### ISSUE TITLE
cfssl command doesn't work in windows command line.  Am I missing something?

### ISSUE THREAD

**Issue by justinbyerss** [cloudflare/cfssl#1188]
![issue](https://user-images.githubusercontent.com/83960583/117740496-ecc7c480-b243-11eb-8a47-2488bad61df2.JPG)

**Comment by nickysemenza** [comment]
If you run go get without the `-u` it should work, right now it's upgrading the dependencies and breaking because one was renamed.

**Comment by justinbyerss** [comment]
> If you run go get without the `-u` it should work, right now it's upgrading the dependencies and breaking because one was renamed.

I tried running the command with out the -u switch, with no success
