### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by aclevername** [cloudflare/cfssl#1203]
hello :wave: 

We (https://github.com/weaveworks/eksctl) use cfssl to create certificate signing requests, thanks for maintaining such an awesome library! We recently got a security warning from dependabot that `cfssl` `v1.6.0` has a  dependency on an insecure package [github.com/dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go/issues/463):
```
$ go mod why github.com/dgrijalva/jwt-go
# github.com/dgrijalva/jwt-go
github.com/weaveworks/eksctl/pkg/addons
github.com/cloudflare/cfssl/csr
github.com/cloudflare/cfssl/helpers
github.com/google/certificate-transparency-go
go.etcd.io/etcd
go.etcd.io/etcd/etcdmain
go.etcd.io/etcd/etcdserver
go.etcd.io/etcd/auth
github.com/dgrijalva/jwt-go
```

We managed to resolve this issue by pointing at master https://github.com/weaveworks/eksctl/pull/4175, where this issue was fixed. It would be great if a new tag could be cut :smile: 

Thanks!
Jake

**Comment by nickysemenza** [comment]
https://github.com/cloudflare/cfssl/releases/tag/v1.6.1 here you go!

**Comment by aclevername** [comment]
Amazing! Thank you 🙏
