### ISSUE TITLE
Require binaries for s390x architecture

### ISSUE THREAD

**Issue by pooja0805** [cloudflare/cfssl#1225]
Hi Team,
I am willing to add s390x support for CFSSL Binaries.
I have observed that `make release` command is used to generate the binaries and it requires cgo which in turn requires a working compiler toolchain for the target platform. It uses cbroglie/goreleaser-cgo:1.12.12-musl image. I had raised an [issue](https://github.com/cbroglie/goreleaser-cgo/issues/2) with [cbroglie/goreleaser-cgo](https://github.com/cbroglie/goreleaser-cgo/issues/2) where they said that it is not maintained anymore.

Any plans of moving [this](https://github.com/cbroglie/goreleaser-cgo/blob/master/Dockerfile) Dockerfile to cfssl / any other public repo?
Also, I came across this issue https://github.com/cloudflare/cfssl/issues/1159. Any updates here?

**Comment by pooja0805** [comment]
Gentle reminder.

**Comment by pooja0805** [comment]
Hi @nickysemenza] Could you please take a look and provide some insight?

**Comment by nickysemenza** [comment]
HI, in https://github.com/cloudflare/cfssl/commit/bba3a2015ca4ad91f5b2c61c5876f0ecbfcb39bc I switched to using a different builder docker image, which it looks like might support s390x by the looks of https://github.com/gythialy/golang-cross/pull/72 - does that make it easier for you to make a PR?

**Comment by pooja0805** [comment]
Sure thanks. I will try building binaries using this image and raise PR with the necessary changes.

**Comment by pooja0805** [comment]
Done via following PR - https://github.com/cloudflare/cfssl/pull/1260. Closing this.

**Comment by huoqifeng** [comment]
@pooja0805 @nickysemenza may I know which release will include the s390x binaries?
