### ISSUE TITLE
add cfssljson to docker image

### ISSUE THREAD

**Issue by batazor** [cloudflare/cfssl#1240]
It would be nice to add cfssljson to the docker image `cfssl/cfssl`

**Comment by nickysemenza** [comment]
all the binaries are there, you simply need to override the [entrypoint](https://github.com/cloudflare/cfssl/blob/master/Dockerfile#L12)

```
docker run --entrypoint cfssljson cfssl/cfssl --help
Usage of cfssljson:
  -bare
    	the response from CFSSL is not wrapped in the API standard response
```
