### ISSUE TITLE
Request a new release

### ISSUE THREAD

**Issue by RainbowMango** [cloudflare/cfssl#1242]
Hi maintainers, 

Thanks for your effort in maintaining this project. Is there a plan for cutting a new release?

I'm asking because the last release is `v1.6.1` which is released almost a year ago, and we want a new tagged release to take #1236. 

cc @nickysemenza

**Comment by nickysemenza** [comment]
yeah totally, i'll make one now!

**Comment by nickysemenza** [comment]
https://github.com/cloudflare/cfssl/releases/tag/v1.6.2 is live now
