### ISSUE TITLE
Adding multiarch support to cfssl docker image

### ISSUE THREAD

**Issue by shahidhs-ibm** [cloudflare/cfssl#1265]
The cfssl docker images supports [amd64](https://hub.docker.com/r/cfssl/cfssl/tags) arch only. Are there any plans to extend its support to other architectures? 

Also we did not got much clarity on how the docker images for cfssl are getting build and published. Could you please elaborate on how its done?

We feel that enabling docker buildx support will be the simplest way to achieve multi-arch support and we would like to provide assistance (if the idea sounds good). Please let us know your thoughts.

**Comment by nickysemenza** [comment]
the docker build process is pretty rudimentary right now - just a make target that pushes to the registry: https://github.com/cloudflare/cfssl/blob/master/Makefile#L69-L73 that I run manually.

I think a github action that builds a multi-arch image (and then pushes to dockerhub) would be great. If you'd like to PR something that builds the image in a Github Action I'd be happy to add in the docker push portion with the relevant secrets!

**Comment by shahidhs-ibm** [comment]
Thanks @nickysemenza for the positive response. We'll work on this feature and create a PR for same.

**Comment by nickysemenza** [comment]
@shahidhs-ibm check out https://hub.docker.com/layers/cfssl/cfssl/master/images/sha256-4eebea119b2c2c0d994f1d0046b7531e510870814b81fd742a9f6512929c8e80?context=repo and let me know if that works!

**Comment by shahidhs-ibm** [comment]
@nickysemenza Thanks for publishing multi-arch images for cfssl.
I am able to pull the cfssl docker image on my s390x arch VM and able to run cfssl commands:
```
$ docker inspect cfssl/cfssl:master | grep -i arch
        "Architecture": "s390x",
        
$ docker run -it --entrypoint cfssl  cfssl/cfssl:master version
Version: 1.6.3
Runtime: go1.20.2
```
All looks good to me. 👍

**Comment by nickysemenza** [comment]
great!
