### ISSUE TITLE
bug: cfssl/cfssl image builds with wrong base arch

### ISSUE THREAD

**Issue by killianmuldoon** [cloudflare/cfssl#1359]
The `cfssl/cfssl:latest` image is currently available for `arm64`, but the base image appears to be `amd64`. This causes issues when trying to run multiple `cfssl` commands with bash.

### Steps to reproduce

On an `arm64` host:

```bash
docker run --entrypoint bash cfssl/cfssl:latest
docker run cfssl/cfssl:latest
```

The first command failes with `exec /bin/bash: exec format error`. The second command runs as expected.  

On an `amd64` host

```base
docker run --platform linux/arm64 --entrypoint bash cfssl/cfssl:latest
docker run --platform linux/arm64 cfssl/cfssl:latest
```

In this case the fist command runs successfully but the second case produces `exec /bin/bash: exec format error` - showing that there are tools with different architectures in the pod.

The solution to this is - I believe - to use a base image that matches the architecture of the target platform.

**Comment by nickysemenza** [comment]
Thanks, https://hub.docker.com/layers/cfssl/cfssl/latest/images/sha256-072d95e1269914c1170f219bf4220b1713a68e13337a16717f9028c91c7a4ccc?context=explore should have your fix in it.

**Comment by killianmuldoon** [comment]
Thank you!
