### ISSUE TITLE
Why is `hostname` needed if we support multiple hosts?

### ISSUE THREAD

**Issue by balupton** [cloudflare/cfssl#138]
My JSON looks like:

``` json
{
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "hosts": [
    "blah.com",
    "bleh.com",
    "blog.com"
  ],
  "CN": "blah.com",
  "names": [
    {
      "C": "asd",
      "L": "asd",
      "ST": "asd",
      "O": "asd",
      "OU": "asd"
    }
  ]
}
```

Why when I want the certificate to support the 3 hosts mentioned in my javascript file, I need to:

1. Specify hostname in: `cfssl gencert -ca $c_cert -ca-key $c_key $c_hostname $c_json | cfssljson -bare ca`?
1. Specify `CN` in my json file?

**Comment by lziest** [comment]
We are currently doing development for supporting multiple hostnames in the command line tool more intuitively and clearly. The doc needs a few updates and I will do it as soon as code logic settles down.

**Comment by gmanfunky** [comment]
For the current codebase, using the command line you can get multiple hostnames into the cert by separating them with a comma. The hosts array in the json was apparently used to create the CSR, but the cert signer didn't seem to get the message until i specified it on the cli. 

{code}
cfssl gencert -config profiles.json -ca dev-intermediate.pem -ca-key dev-intermediate-key.pem -profile client-server mydomain.gabe.hello,hello.gabe.mydomain,127.0.0.1 mydomain.gabe.hello.json | cfssljson -bare mydomain.gabe.hello

openssl req -in mydomain.gabe.hello.csr -text -noout
<shows SAN domains from the .json>

openssl x509 -in mydomain.gabe.hello.pem -text -noout
<shows SAN domains from the cli if more than one was provided>
{code}

**Comment by lziest** [comment]
I have made changes to remove the mandatory 'hostname' argument in CLI gencert and sign. And yes you can supply a optional hostname list through '-hostname' flag with a comma-separated hostname list to override the hosts in the cert.
With the recent changes, consider this issue fixed.

**Comment by balupton** [comment]
Awesome thanks!
