### ISSUE TITLE
Flag.Usage is nil, causes panic

### ISSUE THREAD

**Issue by FiloSottile** [cloudflare/cfssl#167]
For some reason I don't understand, flag.Usage is set to nil in main.

Then in cli.Start:

```go
	flag.Parse()
	if flag.Usage == nil {
		flag.Usage = func() {
			fmt.Fprintf(os.Stderr, usage)
			for name := range cmds {
				fmt.Fprintf(os.Stderr, "%s\n", name)
			}
		}
	}
```

`flag.Parse` panics if it has to call Usage (like when you have a wrong flag). The quick fix is to move it under the if, but I'm afraid there are other calls of flag functions that might fail around.

**Comment by grittygrease** [comment]
@kisom has this been resolved? If so, please close the issue.
