### ISSUE TITLE
Update installation instructions for RHEL-like linux distributions

### ISSUE THREAD

**Issue by dr107** [cloudflare/cfssl#169]
Because of patents on elliptic curve crypto, Red Hat patches the golang distributions in its repos to remove it. Therefore, users of linux distributions based on Red Hat (Fedora, SUSE, etc) will have to install golang manually for CFSSL to build. This should be mentioned in the README, or people will not know why CFSSL fails to build.

**Comment by dr107** [comment]
I don't know how to assign myself to things, but I'll be handling this.

**Comment by kisom** [comment]
Covered in #170.
