### ISSUE TITLE
User authentication system

### ISSUE THREAD

**Issue by slantview** [cloudflare/cfssl#175]
We would like to implement a user authentication system with an LDAP provider as the authentication backend. The only issue is that once you pass your credentials, you should be able to authenticate further requests based on some sort of session key.

It would be nice to have a configurable session timeout, and also support service tokens so other services could use this as well.

Would this be an addition that you guys would like to support? I can code this, but trying to determine if I should build it separately.

Thanks,
Steve

**Comment by grittygrease** [comment]
Hi Steve,

Integrating a more complex authentication provider is not in our current roadmap. That said, we would be happy to accept a fully functioning piece of code to handle that here, as long as you are available to support and debug users who want to use it.

Nick

**Comment by csnook** [comment]
I'd be very interested in implementing a feature that requires that specified fields match a specified HTTP header. That way you could implement arbitrary authentication in a frontend, but that frontend wouldn't need to be modified to parse the JSON request or the CSR encoded within it. For example, you might put something like this in your config.json:

`{
  "header_match": {
    "CN": "X-Authenticated-User",
    "hosts": "X-Authenticated-User"
  }
}`

Then you'd configure your frontend to pass the X-Authenticated-User header set to whatever they authenticate as (lots of auth systems already do this), and be confident that you're only issuing certificates with an authorized CN or SAN. I'd like to get a comment on the interface before I start working on it though.

**Comment by smithbk** [comment]
@csnook Chris, did you do this work?  Any update on supporting LDAP?

**Comment by csnook** [comment]
No, we ended up doing authentication in Nginx. It wasn't a very good solution though, and certainly not something I'd want exposing to semi-trusted users who should be able to get certs for some CNs and not others.
