### ISSUE TITLE
Ambiguous error returned by 'cfssl sign'

### ISSUE THREAD

**Issue by hwh33** [cloudflare/cfssl#197]
When you run 
    'cfssl sign -ca ca-cert.pem -ca-key ca-key.pem cert_request.pem'
and you supply a malformed certificate request, you receive an error stating 'failed to decode certificate'.  I think that this should say 'failed to decode certificate request' as otherwise the user is probably going to try and figure out what's wrong with their CA certificate.

**Comment by lziest** [comment]
I believe this is fixed.
