### ISSUE TITLE
Revocation

### ISSUE THREAD

**Issue by ghost** [cloudflare/cfssl#2]
First of all: thanks for the release! 

I don't see anything in the CA functionality about revoking signed certificates, is this because revocation isn't really useful or is it for another reason?

**Comment by F21** [comment]
Any progress on this one?

**Comment by kisom** [comment]
No progress, but it's been added to the [1.2 release task
list](https://github.com/cloudflare/cfssl/milestones/Release%201.2)
(we're planning on releasing 1.1 by the end of the month).
