### ISSUE TITLE
IP Address Alternate Name

### ISSUE THREAD

**Issue by TheDeadCode** [cloudflare/cfssl#209]
Hi! It seems that IP address in the subject alt name is not supported.

Please see [here](http://tools.ietf.org/html/rfc2818) on section 3.1 paragraph 5.

 > In some cases, the URI is specified as an IP address rather than a
   hostname. In this case, the iPAddress subjectAltName must be present
   in the certificate and must exactly match the IP in the URI.

**Comment by lziest** [comment]
Hi @TheDeadCode, we add the support to the signer, which is capable to override the hostname/IP addresses, check [here](https://github.com/cloudflare/cfssl/blob/master/signer/local/local.go#L151)
However, we haven't add the support to the csr package. We will fix it now.

**Comment by lziest** [comment]
Should be solved.
