### ISSUE TITLE
Code Signing Key Usage

### ISSUE THREAD

**Issue by TheDeadCode** [cloudflare/cfssl#224]
Hi! Is it possible to add code signing to certificate usage in the JSON string, so we can generate code signing certs? Thanks

**Comment by kisom** [comment]
Hello. Code signing is enabled with the usage string "code signing":

```
{
    "signing": {
        "default": {
            "expiry": "168h"
        },
        "profiles": {
            "release": {
                "usages": [
                    "signing",
                    "key encipherment",
                    "code signing"
                ]
            }
        }
    }
}
```

If you sign with this configuration using the `release` profile, your certificate will include the code signing usage.
