### ISSUE TITLE
OCSP Responder should return cache-control headers

### ISSUE THREAD

**Issue by jcjones** [cloudflare/cfssl#232]
[responder.go:130](https://github.com/cloudflare/cfssl/blob/master/ocsp/responder.go#L138) should set a cache control header. Something like:
`Cache-Control: public, max-age=[seconds remaining of validity]`

**Comment by ccppuu** [comment]
I think this issue has been resolved since 041286c8347240d76f16e5ff14fa8b686c279f10 and can be closed.

**Comment by kisom** [comment]
Thanks, @ccppuu.
