### ISSUE TITLE
Add concurrency to scan on multiple sites

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/cfssl#236]
When scanning a list multiple sites, scan cycles through the target sites sequentially. Any one scan that has network issues will hold up the rest of the scan. This should be done in parallel to speed up large scans.

**Comment by jacobhaven** [comment]
I find it very rare that I'll run the scan CLI tool against multiple hosts. And from the API, we only support scanning one host per API call (with the possibility of multiple concurrent calls).

More useful would be running multiple scans against the same host concurrently, and streaming the results back to some sort of aggregator that will print them or return them via the API (sadly, we don't have a great way of streaming API results using JSON)

**Comment by taravancil** [comment]
Thanks for the clarification, Jacob. I have multiple scans running per host, which as you suggested, is as major performance win. I'm now working on building an aggregator so that whatever results are available at timeout are still printed.
