### ISSUE TITLE
Any change for another tagged release that is newer?

### ISSUE THREAD

**Issue by ekristen** [cloudflare/cfssl#243]
Main reason: Would love to get this tool put into homebrew for OSX.

**Comment by kisom** [comment]
There's three things we're waiting on for the 1.1 release:

1. IP-based whitelisting for the multiroot CA
2. Hostname regexp filtering
3. Improvements to the scan and bundle UIs

Once these are done, we'll cut the new release.

**Comment by ekristen** [comment]
Sounds great!

**Comment by kisom** [comment]
@ekristen Tag [1.1.0](https://github.com/cloudflare/cfssl/tree/1.1.0) has been pushed.
