### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kisom** [cloudflare/cfssl#248]
One of the most common complaints about CFSSL is that the documentation isn't up to par. We should fix that.

**Comment by kisom** [comment]
As a start, the following would be useful:

* in-depth bootstrap
* api.txt covering endpoints and API client, API authentication
* config.txt: CFSSL configuration, multiroot configuration, CSR format
* ops.txt: a guide for running CFSSL/multiroot in production

Also covered under this issue is a mechanism for default configurations. We'll need to figure out the best way to do this.

**Comment by hebrew878** [comment]
can somebody guide me on how to generate certificates for https:// websites?

**Comment by ekristen** [comment]
+1 to documentation update

It would be nice to see the build documentation updated on how to build locally.

**Comment by ekristen** [comment]
@kisom any idea on when this documentation update is going to occur?

**Comment by hebrew878** [comment]
may be after 2 years

**Comment by kisom** [comment]
@ekristen We're trying to finalise the 1.1 release, which the documentation is a part of. It should be done by the end of the month.

**Comment by kisom** [comment]
There's now some documentation, certainly room for improvement. 1.2 should see a lot more documentation.
