### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hebrew878** [cloudflare/cfssl#253]
why i am getting this error when i run go get -u github.com/cloudflare/cfssl/cmd/cfssl

directory "/root/go/src/regexp" is not using a known version control system
?

**Comment by kisom** [comment]
It means your Go installation isn't set up correctly; it might be useful to go through the [installation instructions](http://golang.org/doc/install) to troubleshoot.

**Comment by hebrew878** [comment]
i think i have installed it correctly.
root@xxx:~# go run test.go
hello, world

test script running correctly .

**Comment by mynameiscfed** [comment]
Check your $GOPATH/src for any projects that are not tracked with git. You can usually fix this error with the godeb command. It should not at all be related to cfssl. Also - it looks like your are using a GOPATH of /root/go/src/regexp ... try  /root/go/src/.

HTH

**Comment by hebrew878** [comment]
I removed another version of golang installed using apt-get install golang
now it is working.
