### ISSUE TITLE
crashers found by `go-fuzz`

### ISSUE THREAD

**Issue by dgryski** [cloudflare/cfssl#279]
cfssl includes a mostly vendored copy of Azure/go-pkcs12.  I just filed  https://github.com/Azure/go-pkcs12/issues/25 that might affect cfssl too.

**Comment by kisom** [comment]
@dgryski Thanks for the heads up. We'll keep an eye out for patches upstream and investigate patching our copy.

**Comment by dgryski** [comment]
Azure/go-pkcs12 has now been merged into /x/crypto: https://github.com/golang/crypto/commit/c8b9e6388ef638d5a8a9d865c634befdc46a6784 , including fixes for these crashers.  Consider moving to that code base instead?

**Comment by dgryski** [comment]
Closing since cfssl now uses /x/crypto/pkc12 which has fixes for these crashes.
