### ISSUE TITLE
go get fails due to LTDL dependency

### ISSUE THREAD

**Issue by gtank** [cloudflare/cfssl#280]
Installation on Fedora 22:
```
$ go get -u github.com/cloudflare/cfssl/cmd/cfssl
# github.com/miekg/pkcs11
../../../../golang/src/github.com/miekg/pkcs11/pkcs11.go:26:18: fatal error: ltdl.h: No such file or directory
compilation terminated.
```

The dependency is documented in BUILDING but not in the installation instructions. Specifying `go get -tags nopkcs11` works. It's an easy change to the installation instructions, but maybe PKCS11 support should be optional rather than default since it depends on non-Go code?

**Comment by jsha** [comment]
Default PKCS11 support was something we had requested for Let's Encrypt, because it was causing us difficulty managing our vendorized dependencies. Sorry that it is causing trouble for you. :-( As penance, I'll submit a PR adding the dependency documentation to the installation instructions.

**Comment by kisom** [comment]
@jsha Thanks!

**Comment by gtank** [comment]
@jsha Gotcha. I was surprised when this failed, but it's a minor annoyance. Carry on then!

**Comment by LukeHandle** [comment]
Also, on CentOS/RHEL 7, libtool-ltdl-devel is required.
