### ISSUE TITLE
Bundler tests fail on Go 1.5 due to change in TLS chain verification errors.

### ISSUE THREAD

**Issue by jacobhaven** [cloudflare/cfssl#316]
[This commit to crypto/tls](https://github.com/golang/go/commit/3cf15b57f76400b22366ccd8ef5b211c72ab6a7f) makes the [bundle from remote test](https://github.com/cloudflare/cfssl/blob/master/api/bundle/bundle_test.go#L141) return a different error code in Go 1.5 than Go 1.4. (1200 vs. 1220). We should refactor the error checking so that this test works across both Go versions.

**Comment by lziest** [comment]
the special detailed 12xx errors are legacy. I will try to figure out if we still need them.

**Comment by lziest** [comment]
I think it is fine to not enforce the exact behavior here, as long as it is an 12xx error.

**Comment by jacobhaven** [comment]
Fixed by #336 
https://github.com/cloudflare/cfssl/pull/336/files#diff-747729f1d58e47ad0a43c3c3344ed27aL141
