### ISSUE TITLE
Certificate Transparency log client support

### ISSUE THREAD

**Issue by tarcieri** [cloudflare/cfssl#318]
Support logging issued certificates to a Certificate Transparency log server. A Go implementation of a Certificate Transparency log client is available here:

https://github.com/google/certificate-transparency/tree/master/go

Certificate Transparency is useful not only for public CAs, but for internal CAs (especially organizations that maintain many internal CAs) to keep an append-only audit log of issued certificates. This can be used both to detect misissuance via automated processes, or perform forensics after malicious certificates are discovered.

**Comment by kisom** [comment]
This should be complete as of 56c7654dd5dc7623ee557bd7f63a3c95a4abc172.

**Comment by tarcieri** [comment]
Awesome! Great news!
