### ISSUE TITLE
Performance: multiple, persistent session support for pkcs11key

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#322]
Right now, pkcs11key opens a session and logs in for every Sign operation. For best performance, it's better to keep some number of sessions alive long-term. Per discussion at https://github.com/letsencrypt/boulder/pull/795, common practice is to have a thread pool with one session per thread.

I think, using channels and goroutines, we can achieve this without changing the Sign API to be asynchronous. We would have Sign send a message on a channel that is consumed by one of the goroutines holding an open session, then block on receiving a response on another channel. Possibly the `chan chan` pattern is useful for this: https://tleyden.github.io/blog/2013/11/23/understanding-chan-chans-in-go/.

I'm planning to do this work along with @jmhodges for Let's Encrypt, but I wanted to file an issue here for tracking, and to make sure this sounds like a good plan to you.

**Comment by jacobhaven** [comment]
@jsha It's a bit problematic introducing a blocking backend to the synchronous Sign call. If it times out, the sign will just fail.

We have been looking into support asynchronous signers ([sketched out here](https://github.com/cloudflare/cfssl/commit/495b3ea848e31a780e7d36b976bb6c35d82e8088)), but this will require a bit more work: Generation of unique asynchronous callback tokens, a thread-safe map from these tokens to `RetryError`, and an API that returns these tokens and another that accepts them to retry the sign operation (calling `RetryError#Retry()`)

**Comment by jsha** [comment]
@jacobhaven: To be clear, this would not be a remote backend, but would be multiple threads of the same process, communicating with Go channels. I don't think there's a risk of timeouts there. There is a risk that the processing thread might have an error but fail to report that error on the response channel, but I think we can avoid that with careful programming and use of `defer`.

Out of curiosity, what is your use case for Asynchronous Signers?

**Comment by jacobhaven** [comment]
@jsha That seems reasonable then, as long as you can rely on your PKCS11 signer to return in a reasonable time.

Asynchronous signer's would be largely useful as a primitive in communicating with external CAs (which have natively asynchronous APIs).
