### ISSUE TITLE
Change how CFSSL uses PKCS#11 keys?

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#335]
In https://github.com/cloudflare/cfssl/pull/330 I added some docs on how to use PKCS#11 keys. There are a few problems:
 - Configuration is inconsistent between OCSP and Signer. This is my fault since I wrote the PKCS#11 / OCSP integration and didn't update Signer to match.
 - There is a proliferation of PKCS#11 config objects, each containing fields like module, token label, pin, etc. This duplication is unfortunate.

In practice, for Let's Encrypt, we use CFSSL in-process, not remotely. So we just call pkcs11key.New ourselves with the parameters we need, and pass the resulting Signer to ocsp.NewSigner and local.NewSigner. The problem with this approach is that it doesn't work in cli or remote modes, since setting up the NewSigners requires custom Go code. Are there people who need to use PKCS#11 in either of those modes? If not, it might be possible to remove explicit support for configuring PKCS#11, which would simplify some interfaces.

Alternately, I see CFSSL now has support for pkcs11uri. It might make sense to consolidate the configuration mechanisms on pkcs11uri, so we don't need the various config types: each type of signer could just accept a pkcs11uri. If we wanted to get really magic, we could change the 'file' config param for local signers to be a URI, and choose between file or PKCS#11 based on the URI scheme.

**Comment by kisom** [comment]
I like the URI-based key selection approach; it seems this will make it easier in the future to adapt new private key systems by adding the handlers for the appropriate scheme. The `multirootca` actually [takes this approach](https://github.com/cloudflare/cfssl/blob/master/cmd/multirootca/config/config.go#L110), for example.
