### ISSUE TITLE
Add checksum file to https://pkg.cfssl.org/

### ISSUE THREAD

**Issue by dol** [cloudflare/cfssl#341]
Add a checksum file to the https://pkg.cfssl.org/ download page. For additional integrity checks a PGP signature of the sha256 checksum could be added.

https://www.unified-automation.com/downloads/pgp-signatures.html

**Comment by kisom** [comment]
@jacobhaven has added this: https://pkg.cfssl.org/R1.1/SHA256SUMS / https://pkg.cfssl.org/

**Comment by dol** [comment]
Much appreciated.
