### ISSUE TITLE
Make hosts not required in CSRs

### ISSUE THREAD

**Issue by thesamet** [cloudflare/cfssl#353]
For many applications a list of hosts is not required in a certificate (the CN is sufficient).

Would you take a pull request that removes this validation?

**Comment by jacobhaven** [comment]
This seems fine. There are certainly usages that don't require SANs to be included in the cert. It would be good to emit a warning if the cert won't satisfy the [CA/Browser Forum Baseline Requirements](https://cabforum.org/wp-content/uploads/Baseline_Requirements_V1_1_6.pdf)
I.e.: If it has the `server auth` key usage, then emit a warning if the certificate has no SANs.

**Comment by j-delaney** [comment]
I am working on this
