### ISSUE TITLE
Create a script that recreates all test certificates in bundler tests

### ISSUE THREAD

**Issue by lziest** [cloudflare/cfssl#356]
Given 'cfssl sign' is mature enough to be used as a CLI CA, we should create a script that generates test certificates that are used in bundler tests. Most bundler test certificate will expire in 2019. Have a script ready will greatly help.

**Comment by jacobhaven** [comment]
Maybe earlier? Right now `bundler_test`'s `TestECDSAWarning` is failing: https://travis-ci.org/cloudflare/cfssl/builds/84421699

**Comment by lziest** [comment]
solved.
