### ISSUE TITLE
Accept TLS Feature (aka OCSP Must Staple) in CSRs

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#390]
The spec that began life as OCSP Must Staple has landed now as TLS Feature: https://tools.ietf.org/html/rfc7633. It would be great if CFSSL supported copying this extension from CSRs. Since it's a new extension, it will probably require some custom ASN.1 marshaling, at least until Go adds native support.

**Comment by grittygrease** [comment]
@jsha, is this covered by https://github.com/cloudflare/cfssl/pull/428 ?

**Comment by jsha** [comment]
Yep!
