### ISSUE TITLE
Problem verifying ocsp responses using openssl

### ISSUE THREAD

**Issue by fastest963** [cloudflare/cfssl#401]
I originally posted about this in #309 but it got no response so I'm reposting as an issue now. When verifying ocsp responses using openssl it fails to parse and throws an error.

```
# cfssl ocspsign -ca ca.crt -responder resp.crt -responder-key resp.key -cert test.crt | cfssljson -bare ocsp
# openssl ocsp -text -respin ocsp-response.der
OCSP Response Data:
    OCSP Response Status: successful (0x0)
Error parsing response
140533419181984:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1342:
140533419181984:error:0D06C03A:asn1 encoding routines:ASN1_D2I_EX_PRIMITIVE:nested asn1 error:tasn_dec.c:854:
140533419181984:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:774:Field=producedAt, Type=OCSP_RESPDATA
140533419181984:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:774:Field=tbsResponseData, Type=OCSP_BASICRESP
140533419181984:error:0D0C706E:asn1 encoding routines:ASN1_item_unpack:decode error:asn_pack.c:189:
    Response Type: Basic OCSP Response
```

I just retested against the latest master and the above still happens.

**Comment by lziest** [comment]
I am looking at OCSP stuff right now. Will give it a try.

**Comment by lziest** [comment]
I tried with Ubuntu 14.04, and it works fine.
1. I create a CA cert and key from 'cfssl gencert -initca ca_csr.json', and proceed to generate test.crt with the CA cert. 
2. I generate a ocsp signer cert/key from the CA, and futher generate a test certificate from the CA.
3. I generate ocsp respose using the ocsp signer key for the test certificate.
4. I verify the ocsp response with
'openssl ocsp -respin ocsp-response.der -text -VAfile ocsp-signer.pem'. 

It works fine, the output:

OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = Example Inc., OU = OCSP Signer, L = San Francisco, ST = California, CN = (dev use only)
    Produced At: Oct 27 06:05:00 2015 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 54A2638573CB90EACECF9E4B120BB4915EC03DEA
      Issuer Key Hash: 406C8DCE43025220B940BA9F312F83873BBC1319
      Serial Number: 3E5BF920B08E33F5
    Cert Status: good
    This Update: Oct 27 06:00:00 2015 GMT
    Next Update: Oct 31 06:00:00 2015 GMT

    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:eb:b8:c0:f5:27:03:0d:0e:5c:3c:c0:70:9a:
         a3:0e:fd:38:62:fb:05:32:2d:2c:a1:e5:ab:48:fb:b7:fa:f9:
         88:02:21:00:d2:c1:50:3d:ba:f8:b3:5c:57:ee:af:0d:9d:4a:
         57:7e:50:98:c5:e4:08:92:69:76:db:6a:6a:e1:ca:d1:f4:25
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 7055590703497034299 (0x61ea7e5cda7d3a3b)
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=US, O=CloudFlare, Inc., OU=CloudFlare Key Services, L=San Francisco, ST=California, CN=(dev use only)
        Validity
            Not Before: Oct 27 06:01:00 2015 GMT
            Not After : Apr 26 18:01:00 2016 GMT
        Subject: C=US, O=Example Inc., OU=OCSP Signer, L=San Francisco, ST=California, CN=(dev use only)
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:20:f2:13:53:a6:18:e7:4c:fd:ac:d5:2f:81:aa:
                    66:34:72:b9:3b:89:6a:66:38:16:0f:23:7b:5b:e4:
                    13:96:bd:f7:85:88:8f:04:e4:5a:d5:4c:0f:b2:63:
                    38:14:57:bb:77:ca:cf:86:1d:d2:25:de:a4:9f:03:
                    1f:e2:a6:02:9a
                ASN1 OID: prime256v1
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                6B:70:2A:87:92:3E:00:2F:A7:ED:A3:A3:7C:DA:CC:09:E3:85:3A:52
            X509v3 Authority Key Identifier:
                keyid:40:6C:8D:CE:43:02:52:20:B9:40:BA:9F:31:2F:83:87:3B:BC:13:19

            X509v3 Subject Alternative Name:
                DNS:www.example.com, DNS:example.com, DNS:*.example.com
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:f5:50:9a:be:9d:b7:30:8b:9b:be:03:69:41:
         0c:5d:08:fc:f5:e8:43:4b:2f:6e:e8:ae:97:db:4e:85:b2:c8:
         f3:02:20:7d:e7:72:21:7b:bf:ed:5f:de:b2:ca:95:da:ec:cf:
         13:de:77:01:32:78:ff:f8:f3:c9:a8:be:f4:b8:cb:d0:51
-----BEGIN CERTIFICATE-----
MIICtzCCAl2gAwIBAgIIYep+XNp9OjswCgYIKoZIzj0EAwIwgZAxCzAJBgNVBAYT
AlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMSAwHgYDVQQLExdDbG91ZEZs
YXJlIEtleSBTZXJ2aWNlczEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzETMBEGA1UE
CBMKQ2FsaWZvcm5pYTEXMBUGA1UEAxMOKGRldiB1c2Ugb25seSkwHhcNMTUxMDI3
MDYwMTAwWhcNMTYwNDI2MTgwMTAwWjCBgDELMAkGA1UEBhMCVVMxFTATBgNVBAoT
DEV4YW1wbGUgSW5jLjEUMBIGA1UECxMLT0NTUCBTaWduZXIxFjAUBgNVBAcTDVNh
biBGcmFuY2lzY28xEzARBgNVBAgTCkNhbGlmb3JuaWExFzAVBgNVBAMTDihkZXYg
dXNlIG9ubHkpMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIPITU6YY50z9rNUv
gapmNHK5O4lqZjgWDyN7W+QTlr33hYiPBORa1UwPsmM4FFe7d8rPhh3SJd6knwMf
4qYCmqOBrjCBqzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEw
DAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUa3Aqh5I+AC+n7aOjfNrMCeOFOlIwHwYD
VR0jBBgwFoAUQGyNzkMCUiC5QLqfMS+Dhzu8ExkwNgYDVR0RBC8wLYIPd3d3LmV4
YW1wbGUuY29tggtleGFtcGxlLmNvbYINKi5leGFtcGxlLmNvbTAKBggqhkjOPQQD
AgNIADBFAiEA9VCavp23MIubvgNpQQxdCPz16ENLL27orpfbToWyyPMCIH3nciF7
v+1f3rLKldrszxPedwEyeP/488movvS4y9BR
-----END CERTIFICATE-----
Response verify OK

openssl version is OpenSSL 1.0.1f 6 Jan 2014

**Comment by fastest963** [comment]
Here are the steps I followed
```
# cfssl genkey -initca csr.json | cfssljson -bare ca
# cfssl gencert -ca ca.pem -ca-key ca-key.pem -config config.json -profile ocsp csr.json | cfssljson -bare ocsp
# cfssl gencert -ca ca.pem -ca-key ca-key.pem -config config.json csr.json | cfssljson -bare test
# cfssl ocspsign -ca ca.pem -responder ocsp.pem -responder-key ocsp-key.pem -cert test.pem | cfssljson -bare ocsp
# openssl ocsp -text -respin ocsp-response.der -VAfile ocsp.pem
```
openssl version is `OpenSSL 1.0.1e-fips 11 Feb 2013`. I'm running it on CentOS 7.1 64-bit.

Here's all the files that were generated in this process including the final response file: http://cl.ly/2Z2S2U2C0Z33 

Could it just be something with the OpenSSL version? Or am I doing something wrong with the process above?

**Comment by fastest963** [comment]
I just tried it with a newer OpenSSL version: `OpenSSL 1.0.1k 8 Jan 2015` and I'm still getting the same error so something must be wrong with how I'm generating the response?

**Comment by fastest963** [comment]
Okay so looks like I found the problem. Upgrading to Go 1.5.1 seems to fix the problem but I'm not sure why. The only difference in the responses between Go 1.4.2 and Go 1.5.1 is that 1.4.2 uses `UTCTime` and 1.5.1 uses `GeneralizedTime`.

[Go 1.4.2 Response](http://lapo.it/asn1js/#3082060C0A0100A08206053082060106092B0601050507300101048205F2308205EE3081EBA003020100A16B3069310B3009060355040613025553311F301D060355040A1316496E7465726E657420576964676574732C20496E632E310C300A060355040B1303575757311630140603550407130D53616E204672616E636973636F311330110603550408130A43616C69666F726E6961170D3135313032373038323630305A306830663041300906052B0E03021A050004141D82D97857C3F1721253B1B004EAE949C85641CC041493F859EBB52344131683ADCF11931CDDFD03CB8702082053BC5069C75A7F8001FF170D3135313032373038303030305AA00F170D3135313033313038303030305A300D06092A864886F70D01010B050003820101006BD6187A6A7AE08888E57EBC3F78D0A40FFE65DFDD286B83103791D79AA417C0F394183556C76F638FA5965C1954DE39ABE510C6D10BA0F0AF98400CE00F618F6E645EC6B975EEB2F86289E32C22A1A8EA4AB33DB3042942F35AE96A539A987D3B9F67263ECB3E4F7B35668195A894E34F0032FA94669E867654025543D24C30D032FF92D841A099BF48A4D5B745D1BF7274ADBE8D93E6D7BCEFF427F1D41949B34D07E85F386B1AAD4EA146FBF07476003A107F4472A74C0B6A6A6B4C9F83ACB5B414FA8876D4C8F1DA292D4457650DF9AD7840F18C75325284D22A6BA57E516F99C4A4A1BFD3F330759147B9241B151B33EAFD85AD76EC6F0B1D1F3BCF7BF3A08203E8308203E4308203E0308202CAA00302010202082B0C29B144F56248300B06092A864886F70D01010B3069310B3009060355040613025553311F301D060355040A1316496E7465726E657420576964676574732C20496E632E310C300A060355040B1303575757311630140603550407130D53616E204672616E636973636F311330110603550408130A43616C69666F726E6961301E170D3135313032373036333730305A170D3135313132363036333730305A3069310B3009060355040613025553311F301D060355040A1316496E7465726E657420576964676574732C20496E632E310C300A060355040B1303575757311630140603550407130D53616E204672616E636973636F311330110603550408130A43616C69666F726E696130820122300D06092A864886F70D01010105000382010F003082010A0282010100C5EA931F1807C999C33DCCC4B16184C89D18C7D34BF97ADFAE5328AC4C94EFC3D406994CFE4D264CCF2DA3908D238E5426E4C43E78D3C8DB4BA955AD2639CACB53502FD0C3017C4E803962B3A7ACF1FDD99467B3759B4525AF210B6BD1FAD0AE15889C75C88B8179983D021D627D1EEBA72028EB7D3A11599061C0EE8BDEB72C71596391127FE3298D9C9262CBB51AE786E2B396B9B7654F723829752FD467A55A6933BBB64FABD934481350A7BDE51F9966FF1DEDA4F3B6CD2785DACADECA24F5DFED2B7579B921D95CDF0159226A01255C22434BAED08126080D24E77767BAAF1D63EB30399038C1EB852D371414BD6B184E01EC226AD74F0FC8A5DDB9F76B0203010001A3818F30818C30130603551D25040C300A06082B06010505070309300C0603551D130101FF04023000301D0603551D0E04160414157731D3EB7976A7076B8B918B92103E00CADDE5301F0603551D2304183016801493F859EBB52344131683ADCF11931CDDFD03CB8730270603551D110420301E820B6578616D706C652E636F6D820F7777772E6578616D706C652E636F6D300B06092A864886F70D01010B038201010099CA6DF9D7BDC4E059D462D543F419CE050D0E77386C17303485D52AD0B39BAB1B380D14AFF923E5DCCC08429FAF7AB627A9285B3F4FDD38832DAF3EA59FA133C049131BC6CAD6C0924391D833E9BFFE22AFB98D22CDC372BE7F5A24D887CFDD58A3B881FF35DE11CB4AEF965365D5690971686C904796C3C9ED6E03FC54EEC51188B1574CD6C326F6C32EC19EFA6C9D629D382E08C79F5D0FBE302E95309A9D3FA9CE36500AC04A898E298D61B182F2CF9E9B9EB0EFB80DE7257B2A84EAA8B91734710407366F5F77D73BCD5B43A14C4BE38370C681B34B924486947B16C32CCFD44B8E98D8F3066FBFF6EBB564729D9A409B986BA60EA8A454ECBEFFBCA7F8)
[Go 1.5.1 Response](http://lapo.it/asn1js/#308206110A0100A082060A3082060606092B0601050507300101048205F7308205F33081F0A003020100A16B3069310B3009060355040613025553311F301D060355040A1316496E7465726E657420576964676574732C20496E632E310C300A060355040B1303575757311630140603550407130D53616E204672616E636973636F311330110603550408130A43616C69666F726E6961180F32303135313032373038323530305A306B30693041300906052B0E03021A050004141D82D97857C3F1721253B1B004EAE949C85641CC041493F859EBB52344131683ADCF11931CDDFD03CB8702082053BC5069C75A7F8000180F32303135313032373038303030305AA011180F32303135313033313038303030305A300D06092A864886F70D01010B050003820101007C41323835CE5E03F272A1B76ECE84D7CE86CE1653DD23201A8040FDF36FF444CD2EEFD6A071AE3DB5FAEC0D79855ACD7B15585F41C757035194A83F76AB27F3CAF16FE91F921E84826456CC854CC7BDEA455C1782F6E36694D73FAFF28E08607C866EA6C41B96E2D3D9E269F06CF4BABD668E54E6B1E87DE9687205DCDEC6F24DAF97EADC51E46DBCC99D8793B411FA3A1A9552A1696A45CC1AF40899DA0967245960D0A13A5F769124B93A19BE0E06E4BBB6586733E019E43D52567910373AAD71FB7D15340BBD231AC7C7FF5CE79DD228C31D8D42D2CF5544064DAD33D39FBE13CB1168E42927C4B4A761A9F1635CAC694282784A106F66267D16C3CB3289A08203E8308203E4308203E0308202CAA00302010202082B0C29B144F56248300B06092A864886F70D01010B3069310B3009060355040613025553311F301D060355040A1316496E7465726E657420576964676574732C20496E632E310C300A060355040B1303575757311630140603550407130D53616E204672616E636973636F311330110603550408130A43616C69666F726E6961301E170D3135313032373036333730305A170D3135313132363036333730305A3069310B3009060355040613025553311F301D060355040A1316496E7465726E657420576964676574732C20496E632E310C300A060355040B1303575757311630140603550407130D53616E204672616E636973636F311330110603550408130A43616C69666F726E696130820122300D06092A864886F70D01010105000382010F003082010A0282010100C5EA931F1807C999C33DCCC4B16184C89D18C7D34BF97ADFAE5328AC4C94EFC3D406994CFE4D264CCF2DA3908D238E5426E4C43E78D3C8DB4BA955AD2639CACB53502FD0C3017C4E803962B3A7ACF1FDD99467B3759B4525AF210B6BD1FAD0AE15889C75C88B8179983D021D627D1EEBA72028EB7D3A11599061C0EE8BDEB72C71596391127FE3298D9C9262CBB51AE786E2B396B9B7654F723829752FD467A55A6933BBB64FABD934481350A7BDE51F9966FF1DEDA4F3B6CD2785DACADECA24F5DFED2B7579B921D95CDF0159226A01255C22434BAED08126080D24E77767BAAF1D63EB30399038C1EB852D371414BD6B184E01EC226AD74F0FC8A5DDB9F76B0203010001A3818F30818C30130603551D25040C300A06082B06010505070309300C0603551D130101FF04023000301D0603551D0E04160414157731D3EB7976A7076B8B918B92103E00CADDE5301F0603551D2304183016801493F859EBB52344131683ADCF11931CDDFD03CB8730270603551D110420301E820B6578616D706C652E636F6D820F7777772E6578616D706C652E636F6D300B06092A864886F70D01010B038201010099CA6DF9D7BDC4E059D462D543F419CE050D0E77386C17303485D52AD0B39BAB1B380D14AFF923E5DCCC08429FAF7AB627A9285B3F4FDD38832DAF3EA59FA133C049131BC6CAD6C0924391D833E9BFFE22AFB98D22CDC372BE7F5A24D887CFDD58A3B881FF35DE11CB4AEF965365D5690971686C904796C3C9ED6E03FC54EEC51188B1574CD6C326F6C32EC19EFA6C9D629D382E08C79F5D0FBE302E95309A9D3FA9CE36500AC04A898E298D61B182F2CF9E9B9EB0EFB80DE7257B2A84EAA8B91734710407366F5F77D73BCD5B43A14C4BE38370C681B34B924486947B16C32CCFD44B8E98D8F3066FBFF6EBB564729D9A409B986BA60EA8A454ECBEFFBCA7F8)

So it doesn't seem to be a problem with cfssl but rather, a problem with the internal go libraries.

**Comment by lziest** [comment]
Very likely it is the asn1 parser incompatibilities.
