### ISSUE TITLE
certificate-transparency dependency issue

### ISSUE THREAD

**Issue by jacobhaven** [cloudflare/cfssl#406]
#394 added a dependency on `github.com/google/certificate-transparency/go`

The `github.com/google/certificate-transparency/go/x509` package conditionally includes [platform specific CGO](https://github.com/google/certificate-transparency/blob/master/go/x509/root_darwin.go#L5) that appears to be causing issues (On my OS X and Debian VM):
```
$ go get -u github.com/cloudflare/cfssl/cmd/...
# github.com/google/certificate-transparency/go/x509
../Code/cf-repos/Go/src/github.com/google/certificate-transparency/go/x509/root.go:15: undefined: initSystemRoots
../Code/cf-repos/Go/src/github.com/google/certificate-transparency/go/x509/verify.go:213: c.systemVerify undefined (type *Certificate has no field or method systemVerify)
../Code/cf-repos/Go/src/github.com/google/certificate-transparency/go/x509/verify.go:213: not enough arguments to return
```

```
$ go env
GOARCH="amd64"
GOBIN="/Users/jacob/Code/cf-repos/Go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jacob/Code/cf-repos/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by jacobhaven** [comment]
I think I've solved this by resetting my GOPATH. I'm still not sure what the issue was...

**Comment by jacobhaven** [comment]
This should be fixed by https://github.com/google/certificate-transparency/pull/1006

**Comment by jacobhaven** [comment]
Until that is merged, this can be fixed by setting `CGO_ENABLED=0` and building with `-tags nopkcs11`

**Comment by andrewbuss** [comment]
(The PR linked above was merged; should this be closed?)

**Comment by jacobhaven** [comment]
Yup.
