### ISSUE TITLE
Allow signing policy when generating a new CA with -initca

### ISSUE THREAD

**Issue by ghost** [cloudflare/cfssl#41]
When generating an *intermediate CA*, one could add an OCSP or CRL URL by using signing policies:
```javascript
{
 "signing": {
   "default": {
     "usages": [
       "signing",
       "key encipherment",
       "cert sign",
       "crl sign"
      ],
      "expiry": "4320h",
      "is_ca": true,
      "crl_url": "https://test-ca.sky/ca/sky-ocean-g2.crl",
      "issuer_urls": ["https://test-ca.sky"]
    }
  }
}
```

It would be nice if the same were allowed when generating a root CA, because initca.go currently forces a default signing policy in this case.

**Comment by lziest** [comment]
it can be done on our subcommand 'selfsign' now.
