### ISSUE TITLE
Add configurability to log facility

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#426]
Right now cfssl's log facility allows configuring levels, but as far as I can tell doesn't allow changing where the logs go. In Boulder we're relying on syslog and would like to be able to send logs there. I'd like to add a way for cfssl users to add their own logger.

**Comment by kisom** [comment]
I like this approach, and also would like both the ability to log to a file and to separate INFO and below from WARNING up. It would also be nice to have a logging package that reported the component that was doing the logging (e.g. signer/local).

**Comment by K4lium** [comment]
@jsha Does this meet your needs?
