### ISSUE TITLE
CRL generation

### ISSUE THREAD

**Issue by sigil66** [cloudflare/cfssl#43]
Is this a planned feature?

**Comment by grittygrease** [comment]
Can you try again with this patch to Go:
https://go-review.googlesource.com/#/c/2259/

**Comment by sigil66** [comment]
@grittygrease this issue is in regards to adding a command that will generate a CRL file from an arbitrary batch of certifcates.

**Comment by jedsmith** [comment]
Any progress here? Thanks!

**Comment by databus23** [comment]
I'm also interested in this. Any update on this?

**Comment by kisom** [comment]
We've decided to work on this for version 1.2; the next release is 1.1, so it will be a little while before we dedicate any engineering resources here to work on this.

**Comment by databus23** [comment]
Thanks! I would also look into taking on this issue if this would be welcome.

In general I'm wondering how do you want to implement crls: Do you want to add some kind of persistence for revoked certificates (serial and reason) to cfssl or should the complete list of revoked certificates be provided every time a crl is (re)generated?

**Comment by kisom** [comment]
In general, we prefer not to maintain persistence in CFSSL&mdash;this provides the most flexibility in how the system will be used. It would be better if the list of revoked certificates is provided. I'd intended to support both full and delta CRLs so that the whole CRL doesn't necessarily need to be provided each time.

**Comment by lziest** [comment]
We already have crl package implemented, thanks to William Lewis @wl2002. and we have cli/gencrl and api/crl as well.

**Comment by sigil66** [comment]
:heart:
