### ISSUE TITLE
Usage of unsafe elliptic curves

### ISSUE THREAD

**Issue by chesteroni** [cloudflare/cfssl#450]
CFSSL in https://github.com/cloudflare/cfssl/blob/master/csr/csr.go uses only curves defined in 	"crypto/elliptic" module of the core of go language.
However those NIST curves are considered as unsafe, according to prof. Daniel J. Bernstein (djb):
http://safecurves.cr.yp.to/

Additionally, there is a module that supports more curves, including some safe ones:
https://github.com/golang/crypto

Could you please add support for that module and other curves in cfssl ?
That would definitely help in deploying secure environments based on PKI managed by cfssl :-)

**Comment by grittygrease** [comment]
Thanks for the comment! Unfortunately the DJB curves have not yet been standardized for x509. We'll be happy to include them once the standards are agreed upon.

**Comment by OmegaRogue** [comment]
Any update on this?
