### ISSUE TITLE
Newcert Request Docs

### ISSUE THREAD

**Issue by anniephan** [cloudflare/cfssl#456]
Executing the example request  in the [newcert documentation](https://github.com/cloudflare/cfssl/blob/master/doc/api/endpoint_newcert.txt) now throws an "invalid algorithm" error.

I altered the request from 

```
{    
    "request": {
         "hosts":["www.example.com"], 
         "names":[{"C":"US", "ST":"California", "L":"San Francisco", "O":"example.com"}], 
         "CN": "www.example.com"
     } 
}
```

to

```
{    
    "request": {
         "hosts":["www.example.com"], 
         "names":[{"C":"US", "ST":"California", "L":"San Francisco", "O":"example.com"}], 
         "CN": "www.example.com",
         "key":{"algo":"rsa","size":2048}
     } 
}
```

adding the "key" field and that seems to fix it. The newcert documentation should probably be updated to account this change.

**Comment by jacobhaven** [comment]
The problem was `csr.New()` was creating an invalid Key (`algo` and `size` set to `""`), I've updated it to use the right helper function.
