### ISSUE TITLE
Remote CA renew

### ISSUE THREAD

**Issue by zachaller** [cloudflare/cfssl#473]
I see there is a renewca flag and that works great with files I was wondering and maybe I am miss-understanding this, could there also be a renewca that worked with remotes if we wanted to lets say renew intermediates off a rootca remote.

**Comment by lziest** [comment]
You can check out cli tool sign for renewing/signing a existing CSR from a remote signer. https://github.com/cloudflare/cfssl/blob/master/cli/sign/sign.go

**Comment by lziest** [comment]
I guess I need to update the help message to emphasize that '-renewca' and '-initca' works for root CA only because they are essentially self-signed.

**Comment by zachaller** [comment]
Yup that totally makes sense now that i think about it, that keeps the private key etc just as it would using verisign or someone like that sorry just first time setting up our own CA etc been learning and figuring lots of stuff out while trying to use best practices. Thanks for the help.
