### ISSUE TITLE
Break dependency between signer/local and certdb

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#491]
In https://github.com/letsencrypt/boulder/pull/1397, @hlandau is pulling in the latest CFSSL into Boulder so we can do OCSP extensions (to provide SCTs via OCSP). Unfortunately, that pulls in dependencies on sqlstruct, pq, and go-sqlite3, which we'd rather not pull in.

I believe this is because signer/local now depends on certdb, which depends on those other packages. Is it possible to break that dependency? I think it would probably be ideal if Signer was responsible only for signing, and the code that calls Signer was responsible for storing the result. That way the calling code can implement various storage strategies, retries, and so on.

Thanks,
Jacob

**Comment by lziest** [comment]
we will make signer/local dependents on a interface only certdb package, which only depends on "database/sql", how would that sound?

**Comment by jsha** [comment]
That works for me, thanks!
