### ISSUE TITLE
Split pkcs11key into a separate repo

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#519]
In https://github.com/cloudflare/cfssl/pull/512, we flipped the default of the `pkcs11` / `nopkcs11` build tags. Unfortunately this blocks Boulder from vendoring the latest version of cfssl, because we build with no build tags.

As discussed in https://github.com/cloudflare/cfssl/issues/416, we can split pkcs11key into its own repo. This is probably the best solution: That way users of cfssl can run `go test ./...` without needing to install libtool-ltdl, and additionally users of the pkcs11key package don't need to define any build tags, so long as they install the requirements to build that package (i.e., libtool-ltdl). This would be my preferred way forward.

**Comment by jacobhaven** [comment]
This sounds great. I'm starting the creating of a `"github.com/cloudflare/pkcs11key"` repo. It'll need a new README (explaining the `libtool-ltdl` dependencies) and the removal of the `pkcs11` build tag.

**Comment by jacobhaven** [comment]
@jsha Unless you want to move this code to the [letsencrypt](https://github.com/letsencrypt) organization. That'd probably also be fine.

**Comment by jsha** [comment]
Yeah, that's probably for the best since AFAIK we're the ones that depend on it most heavily, and will be doing the most modifications. In terms of copyright, I'll combine cfssl's LICENSE file and say "parts of this code are (c) Cloudflare, and parts are (c) Let's Encrypt?

**Comment by jacobhaven** [comment]
@jsha I think we're just going to end up making a CF organization repo.

**Comment by jsha** [comment]
Sorry for the delay: I've got it set up this morning (history and all, thanks to `git filter-branch`): https://github.com/letsencrypt/pkcs11key.
