### ISSUE TITLE
How to generate a CSR to generate `server authentication` only certificates?

### ISSUE THREAD

**Issue by codefx9** [cloudflare/cfssl#520]
Hi,
Is it possible to generate a csr request that will only generate `server authentication` only certs? Example:

<img width="488" alt="screen shot 2016-02-20 at 11 52 58 am" src="https://cloud.githubusercontent.com/assets/13058834/13194799/87d73dea-d7c8-11e5-9b88-7365c37f09e6.png">

**Comment by jacobhaven** [comment]
This is covered in the `usage` field of a [CA's Signing Profile](https://github.com/cloudflare/cfssl/blob/master/doc/cmd/cfssl.txt#L86). Specifically, you'd want a profile with `"usage": ["server auth"]`

**Comment by codefx9** [comment]
Thanks for the answer.
