### ISSUE TITLE
Which file is which?

### ISSUE THREAD

**Issue by balupton** [cloudflare/cfssl#526]
I set this up in 2014, but misplaced the instructions I used, so trying to recreate the instructions.

The use case is https://meta.discourse.org/t/allowing-ssl-https-for-your-discourse-docker-setup/13847 and I got this far:

1. Create `csr.json`

    ``` json
    {
      "key": {
        "algo": "rsa",
        "size": 2048
      },
      "hosts": [
        "discuss.bevry.me"
      ],
      "names": [
        {
          "C": "AU",
          "L": "Western Australia",
          "ST": "Perth",
          "O": "Bevry Pty Ltd",
          "OU": "IT"
        }
      ]
    }
    ```

1. Generate `ca-key.pem`, `ca.csr`, `ca.pem`

    ```
    cfssl genkey -initca csr.json | cfssljson -bare ca
    ```

How do I turn those three files into the private key `/var/discourse/shared/standalone/ssl/ssl.key` and cert `/var/discourse/shared/standalone/ssl/ssl.crt`?

Perhaps `cfssl gencert -ca ca.pem -ca-key ca-key.pem csr.json  | cfssljson -bare ssl` with some renaming of some files?

**Comment by jacobhaven** [comment]
`cfssljson -bare ssl` should generate the files `ssl.pem` (you can rename this to `ssl.crt`) and `ssl-key.pem` (you can rename this to `ssl.key`)
