### ISSUE TITLE
Question: AKI

### ISSUE THREAD

**Issue by err0** [cloudflare/cfssl#552]
Is there a way to programmatically retrieve the authority_key_id via API or the `cfssl` command?

so far the only way I've figured out how to get it is via a postgres query:
`select convert_from(authority_key_identifier, 'UTF-8') as aki from certificates;`

As it is now required to revoke a cert I'd love to be able to get it via a command or api.

Thanks!

**Comment by kisom** [comment]
There isn't, right now, but it would be a fairly straightforward change to make.
