### ISSUE TITLE
Auth config "Unknown private key error"

### ISSUE THREAD

**Issue by michaelmack000** [cloudflare/cfssl#556]
I'm getting error "Unknown private key error" when requesting a SSL with auth_key configured.  No problems if no security applied.  Any help would be appreciated.

Command to open endpoint
./cfssl -loglevel 0 serve -ca-key ca-key.pem -ca ca.pem -config ./ca-config.json -address=10.1.120.248

ca-config.json
{
    "auth_keys": {
        "key1": {
            "type": "standard",
            "key": "removedkey"
		}
	},
    "signing": {
        "default": {
            "expiry": "43800h",
            "auth_key": "key1"
        },
        "profiles": {
            "server": {
                "auth_key": "key1",
                "expiry": "43800h",
                "usages": [
                    "signing",
                    "key encipherment",
                    "server auth"
                ]
            },
            "client": {
                "auth_key": "key1",
                "expiry": "43800h",
                "usages": [
                    "signing",
                    "key encipherment",
                    "client auth"
                ]
            },
            "client-server": {
                "auth_key": "key1",
                "expiry": "43800h",
                "usages": [
                    "signing",
                    "key encipherment",
                    "server auth",
                    "client auth"
                ]
            }
        }
    }
}

Client configuration
{
  "auth_keys": {
    "key1": {
      "type": "standard",
      "key": "removedkey"
    }
  },
  "remotes": {
    "caserver": "10.1.120.248:8888"
    },
  "signing": {
    "default": {
      "expiry": "43800h",
      "profile": "client-server"
    },
  "profiles": {
    "client-server": {
      "auth_key": "key1",
      "expiry": "43800h",
      "remote": "caserver",
      "usages": [
        "signing",
        "key encipherment",
        "server auth",
        "client auth"
       ]
     }   
   }
  }
}

Client CSR
{
    "CN": "her01cavesm0001.her.local",
    "hosts": [
        "10.1.120.31",
        "her01cavesm0001",
        "her01cavesm0001.her.local"
    ],
    "key": {
        "algo": "rsa",
        "size": 2048
    },
    "names": [
        {
            "C": "US",
            "L": "CA",
            "ST": "Mountain View"
        }
    ]
}

**Comment by tgenovese** [comment]
I believe your client configuration should use "auth_remote", like this:

```
{
  "auth_keys": {
    "key1": {
      "type": "standard",
      "key": "removedkey"
    }
  },
  "remotes": {
    "caserver": "10.1.120.248:8888"
  },
  "signing": {
    "profiles": {
      "client-server": {
        "auth_remote": {
          "auth_key": "key1",
          "remote": "caserver",
        }
      }
    }
  }
}
```

**Comment by lziest** [comment]
with updated doc, consider this is finished.
