### ISSUE TITLE
Checksum mismatch for 1.2.0 tag archive

### ISSUE THREAD

**Issue by ilovezfs** [cloudflare/cfssl#568]
Was the 1.2.0 tag changed (deleted/recreated)? We're seeing a checksum mismatch now:
https://github.com/Homebrew/homebrew/issues/50603

**Comment by grittygrease** [comment]
Yes, the tag was deleted and recreated due to the fact that the version number was not bumped. Please update the tag.

**Comment by ilovezfs** [comment]
@grittygrease Perfect, thank you.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/commit/8597191acc2965471c3a80cf90b1193efab09e8c
