### ISSUE TITLE
CF IP ranges fail to parse

### ISSUE THREAD

**Issue by szepeviktor** [cloudflare/cfssl#569]
```
root@debian8u:~# go version
go version go1.6 linux/amd64

root@debian8u:~# cfssl -loglevel 0 scan cfssl.org
2016/04/01 19:15:03 [DEBUG] loading configuration file from
Scanning cfssl.org...
2016/04/01 19:15:03 [DEBUG] scan: Couldn't parse CIDR range: invalid CIDR address:
2016/04/01 19:15:04 [DEBUG] scan: tls: DialWithDialer timed out
2016/04/01 19:15:04 [DEBUG] scan: tls: DialWithDialer timed out
2016/04/01 19:15:04 [DEBUG] scan: tls: DialWithDialer timed out
2016/04/01 19:15:04 [DEBUG] scan: tls: DialWithDialer timed out
2016/04/01 19:15:04 [DEBUG] scan: tls: DialWithDialer timed out
```
Please advise.

**Comment by yveslaroche** [comment]
I have the same problem on OSX using 
```
go version go1.6 darwin/amd64
```

**Comment by kisom** [comment]
I just did some cursory debugging, and noted the following:

1. The invalid CIDR address comes from attempting to parse an empty network, which is coming at the end of a list of networks. This is a red herring, and can be ignored (I've got a small changed queued in this investigation that ignores empty lines).
2. The timeouts are happening while trying to get the chain on a few of the connection attempts; it seems to time out and give results after 5 minutes (many of the tests then report timed out).

**Comment by APTy** [comment]
The CIDR parse issue could be related to [cfssl/scan/connectivity.go#L82](https://github.com/cloudflare/cfssl/blob/master/scan/connectivity.go#L82), specifically that a newline (`strings.NewReader("\n")`) is inserted between the IPv4 and IPv6 addresses. Removing this newline fixed the CIDR parsing issue for me, but I am also getting the TLS dialer timeouts.
```
Version: 1.2.0
Revision: dev
Runtime: go1.6
```
