### ISSUE TITLE
Distinction between Critical, Fatal, and Error log levels?

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#582]
I'm working on simplifying the syslog logging in Boulder slightly and removing some of the levels. I notice cfssl's internal error levels include both Critical and Fatal. Is there a distinction between them? I'm guessing Critical is worse than Error, but doesn't terminate the process?

**Comment by kisom** [comment]
Here's my general take on these logging levels:

* Fatal is an uncorrectable error.
* Critical is a serious error that should probably trigger some kind of alert in a monitoring system.
* Error is an error that's not so serious to trigger an alert, but error trends (lots of errors in a short time, for example) might be something to alert on.

**Comment by jsha** [comment]
That's helpful, thanks!

**Comment by jsha** [comment]
Reopening - as far as I can tell, `cmd/multirootca/ca.go` is the only place that actually uses the Fatal from CFSSL's logging package. Would you be open to changing that to use `log.Critical` and remove `Fatal` from the log package? The more I think about it, the more it seems dangerous to have a log level that has a side effect in one log system but may not trigger that side effect in another log system.

**Comment by kisom** [comment]
As far as removing `log.Fatal`, we use the CFSSL logging package in places other than CFSSL and these users do use this function call with the intention of `Fatal` killing the program. I don't really mind removing it from `multirootca` itself though.

Another option is to write a syslog wrapper, though that does seem a bit on the grotesque side. It does preserve the behaviour, though.

**Comment by jsha** [comment]
Ok, sounds like it's not reasonable to remove it. I also realized that my logic was incorrect - because CFSSL's log package calls `os.Exit` itself after calling out to the external logger, the correct behavior will hold. Thanks!
