### ISSUE TITLE
Init_ca API call should return the CSR as well

### ISSUE THREAD

**Issue by fhossain** [cloudflare/cfssl#594]
At the moment init_ca API call returns the self signed certificate and private key. However, for to create intermediate CA we need the CSR to be signed by the root. In the cli version all three are returned but not in the API version. It would be great to have all three returned for API as well.

**Comment by lziest** [comment]
Our intention for initca is really to initialize a root CA, so csr is not really needed. And I think, to satisfy your goal, use api genkey or gencert. https://github.com/cloudflare/cfssl/blob/master/cli/serve/serve.go#L153
And the code behind genkey/gencert is at api/generator.go

**Comment by fhossain** [comment]
@lziest thanks that works. If I can set pathlen to 0 in profile config it will address my intermediate needs. I know pathlen=0 is being worked on as a separate issue, so this issue can be closed.

**Comment by lziest** [comment]
Yes, we are working on that, a pathlen=0 intermediate CA. Closing this.

**Comment by fhossain** [comment]
@lziest I have one more question and it might be easier to ask in this thread instead of opening a new issue. In my environment I am creating an intermediate CA that will create and issue certificates on demand. Since, I expect the load to be high on this intermediate CA, I will need to create multiple CA server instances for scalability and availability. The intermediate CAs will then be load balances either via DNS or more likely by a HW/SW load balancer on the server side. This keeps the clients simple and unaware of the server deployment topology. I was hoping the intermediate CAs to not share any key/data but be issued form the same CA. Under this deployment strategy a request for sign/newcert can go to one intermediate CA and a subsequent request for bundling (to get CA chain) can go to different intermediate CA instances and end up with invalid certificate Chains. I was thinking that sign and newcert could have an option to return the full certificate chain. That does that make sense or is there an easier way to solve this problem?
