### ISSUE TITLE
Add example of calling 'bundle' in the API

### ISSUE THREAD

**Issue by tlianza** [cloudflare/cfssl#603]
The README shows a command-line example for 'bundle' but not an API example.

**Comment by kisom** [comment]
We have some API documentation in 'doc/api/'; how does [endpoint_bundle.txt](https://github.com/cloudflare/cfssl/blob/master/doc/api/endpoint_bundle.txt) look?

**Comment by kisom** [comment]
@tlianza Was that documentation useful?

**Comment by troyfontaine** [comment]
Hi @kisom there isn't any explanation specifically for the option when using the newcert api.  It is mentioned that it is available to provide the bundle and uses a boolean value but doesn't provide an example of where to use it in the api call or how.  Are there any pre-requisites before you can use the bundle option with newcert when using it to generate a certificate?

**Comment by lziest** [comment]
@troyfontaine please raise a new issue, I believe newcert api's bundle option is very specific to a usage where there are multiple CAs behind newcert so a bundle (CA cert + issued cert) is helpful at issuing time.
