### ISSUE TITLE
"content commitment" is misspelled in list of key usage names

### ISSUE THREAD

**Issue by jgoldschrafe** [cloudflare/cfssl#606]
In https://github.com/cloudflare/cfssl/blob/master/config/config.go#L460 and the documentation at https://github.com/cloudflare/cfssl/blob/master/doc/cmd/cfssl.txt#L91, `content commitment` is misspelled as `content committment`. I'd just submit a PR here, but I'm not sure what approach the project owners want to take with respect to backwards compatibility on this.

**Comment by lziest** [comment]
it's good to correct it. It's easy to fix the compatibility as well, since we just need to update the policy.

**Comment by kisom** [comment]
I don't think this usage is widely used in CFSSL and it's better to spell it correctly. However, it is the way it is spelled in Go's [`crypto/x509`](https://github.com/golang/go/blob/master/src/crypto/x509/x509.go#L399) package --- which is where these usages originally came from. It might be better to add an additional, correctly spelled usage, and keep the old one as a fallback.

**Comment by jgoldschrafe** [comment]
It's spelled correctly in the linked line of source, and I wasn't able to find any other references to the `committment` spelling in the Golang source tree.

**Comment by kisom** [comment]
You're right --- I had the two terms flipped around, and wasn't looking at the strings.

**Comment by lziest** [comment]
fixed

**Comment by silverlyra** [comment]
This is still misspelled [in the code](https://github.com/cloudflare/cfssl/blob/437c6213e569dde639fd116272c27557fd38eaf9/config/config.go#L556) and [in the docs](https://github.com/cloudflare/cfssl/blob/437c6213e569dde639fd116272c27557fd38eaf9/config/config.go#L556).
