### ISSUE TITLE
Bundle does not work for client certificates

### ISSUE THREAD

**Issue by fhossain** [cloudflare/cfssl#608]
I could not get bundle to work for client certificates. Running -loglevel 0 I can see the following error -
[DEBUG] verification failed: x509: certificate specifies an incompatible key usage
The problem is that golangs strict extended key usage validation which requires the full chain to allow key usage. Similar problem recommends that Root and Intermediate CA certificates should be created with key usage of "any". However, I could not get initca or sign for intermediate certificates to accept key usage of any.
http://grokbase.com/t/gg/golang-nuts/1412vfsyjg/go-nuts-tls-clientauth-requires-extkeyusageclientauth-through-whole-certificate-chain
It would be great if this was working for client certificates. Bundle works fine for intermediate certificates and servers certificates. My current workaround is to call "info" on the issuer. Then use the issuer certificate to get a bundle. Then manually prepend client certificate to the intermediate CA bundle.

**Comment by lziest** [comment]
should be fixed.
