### ISSUE TITLE
ocsp_url is ignored and no OCSP URL in the generated certificate

### ISSUE THREAD

**Issue by jvermillard** [cloudflare/cfssl#629]
Even if I put in my config file default profile:
"ocsp_url" : "http://something"

No OCSP URL appear in the generated certificate.
I traced the code, everything is fine until the call to https://golang.org/pkg/crypto/x509/#CreateCertificate
in signer/local/local.go

The OCSP URL is in the X509 template but the URL is ignored, it's quite clear in the golang doc:

> The following members of template are used: SerialNumber, Subject, NotBefore, NotAfter, KeyUsage, ExtKeyUsage, UnknownExtKeyUsage, BasicConstraintsValid, IsCA, MaxPathLen, SubjectKeyId, DNSNames, PermittedDNSDomainsCritical, PermittedDNSDomains, SignatureAlgorithm. 

I wonder how this "ocsp_url" is supposed to work?

**Comment by kisom** [comment]
We've been signing certificates that end up with an OCSP URL. Do you have any additional information on your configs that we can use to debug this?

**Comment by jvermillard** [comment]
My configuration:
```
➜  cat server-config.json
{
    "signing": {
        "default": {
            "expiry": "168h",
            "ocsp_url" : "http://localhost:8889",
            "crl_url" : "http://localhost:8888/crl",
            "expiry": "8760h",
            "usages": [
                "signing",
                "key encipherment",
                "client auth"
            ]
        }
    }
}
```

**Comment by jvermillard** [comment]
hmm I can't reproduce it today, probably my fault :( sorry for the time loss
