### ISSUE TITLE
DC not supported

### ISSUE THREAD

**Issue by benileo** [cloudflare/cfssl#651]
Is there any particular reason that domainComponent(DC) is not supported?

> In addition, implementations of this specification MUST be prepared
>    to receive the domainComponent attribute, as defined in [RFC4519].
>    The Domain Name System (DNS) provides a hierarchical resource
>    labeling system.  This attribute provides a convenient mechanism for
>    organizations that wish to use DNs that parallel their DNS names.
>    This is not a replacement for the dNSName component of the
>    alternative name extensions.

**Comment by kisom** [comment]
This was recently raised as #632.

**Comment by benileo** [comment]
Thanks
