### ISSUE TITLE
Tag Docker Hub image with version/release

### ISSUE THREAD

**Issue by bkleef** [cloudflare/cfssl#654]
Currently it's only possible to pull images by following tags: https://hub.docker.com/r/cfssl/cfssl/tags/ where no release number tag is listed.
In other words, it's not possible to pinpoint an image on a specific release. Please update build accordingly.
Thanks a lot in advance!

**Comment by jacobhaven** [comment]
The `1.2.0` tag has now be built (`1.0.0` didn't have a Dockerfile, and the `1.1.0` build failed) I believe new tags should also trigger the appropriate new builds.

CFSSL admins: I think you should have permissions to modify the [Docker Hub config](https://hub.docker.com/r/cfssl/cfssl/~/settings/automated-builds/)

**Comment by kisom** [comment]
I have permissions. Thanks @jacobhaven.
