### ISSUE TITLE
How to generate a ca certificate never expired

### ISSUE THREAD

**Issue by yorksen** [cloudflare/cfssl#655]
Before generate the self-signed ca certificate, there is a property called "expiry" which must be provided via ca-config.json. 

If I want to generate a ca certificate which never expired, is it means I should leave it empty
 "expiry":"" 

or assign it to zero?  
"expiry":"0h"

**Comment by lziest** [comment]
You can't. But practically no one stops you from generating a CA with 10,000 year expiry. However, do keep in mind that attacks against crypto only gets stronger, an never expired production CA is a very bad idea.
