### ISSUE TITLE
Certificate signatures limited by private key size of CA

### ISSUE THREAD

**Issue by itsnotvalid** [cloudflare/cfssl#656]
I tried generating new certificates that use sha256 for signature using a very old CA key/cert pair. The CA's key only uses RSA at 1024 bit, and no matter how I configure cfssl only gives me sha1 signatures on the certificates it generates. Is there a way to override it like openssl does with `-sha256`?

Thanks.

**Comment by kisom** [comment]
Hi @itsnotvalid; CFSSL doesn't give an option to do this. It's assumed that a legacy key size (less than 2048 bits) requires a legacy signature algorithm (in this case, SHA-1).

**Comment by itsnotvalid** [comment]
@kisom this is however simply hard coded in the source code of cfssl. For reference, it is possible to make RSA 4096 cert with a CA of RSA 1024. Would you mind if I create a pull request to support that?

Thanks.

**Comment by kisom** [comment]
@itsnotvalid We don't have a problem with mixing sizes in the chain, but we made the decision not to support keys smaller than 2048 bits.
