### ISSUE TITLE
CRL url generation issue?

### ISSUE THREAD

**Issue by mitchcapper** [cloudflare/cfssl#66]
generating certs with CRL urls seems to have a bit of an issue, it may be more with go than cfssl.  Using this over openssl there seems to be a bit of an issue.  openssl parses the certs and shows the correct CRL url but both firefox and internet explorer seem to have an issue reading the url from the certs generated.  In IE it shows as the hex/ascii value of:
30 2c 30 2a a0 28 80 26
86 24
before the http:// of the url) FF just doesn't show any url.
the bundler decodes it fine and validates without issue.

**Comment by grittygrease** [comment]
Could it be related to this change?
https://go-review.googlesource.com/#/c/2259/

**Comment by mitchcapper** [comment]
If that is a backport from a 1.4 change maybe as it does address the crl, however it looks like that is in master, and it atleast is working in IE with standard 1.4 already.
