### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by akerl** [cloudflare/cfssl#663]
It looks like there have been a lot of improvements to the codebase since 1.2 was released. I specifically noticed the gap between HEAD and the 1.2 tag when I tried to build the last released version and the build script was vastly different.

Would it be possible to cut a new 1.3 or similar from the current master branch?

**Comment by kisom** [comment]
@akerl We are currently doing a review to prepare for a 1.3 release.

**Comment by kisom** [comment]
FYI this is being tracked in [this project](https://github.com/cloudflare/cfssl/projects/1).

**Comment by akerl** [comment]
Ping?

**Comment by cbroglie** [comment]
Some good news here: https://github.com/cloudflare/cfssl/issues/995#issuecomment-548473012. Follow #995 for additional updates.
