### ISSUE TITLE
AuthorityKeyID is no longer being set in Go 1.7 for self-signed certificates

### ISSUE THREAD

**Issue by alexbrand** [cloudflare/cfssl#664]
I upgraded to 1.7 and one of my tests started failing. I tracked it down to this change in Go 1.7.

I am not sure if it needs to be handled in any way in cfssl, or maybe add documentation around it.

https://go.googlesource.com/go/+/b623b71509b2d24df915d5bc68602e1c6edf38ca

**Comment by kisom** [comment]
It looks like this is only in self-signed certs. Generally agree with agl's thoughts on it. I'll submit a PR to update the docs.
