### ISSUE TITLE
Downloading root cert

### ISSUE THREAD

**Issue by chrisb3ll** [cloudflare/cfssl#679]
Hi, apologies if this is a stupid question, I've spent a long time trying to work this out. 😞 

I'm standing up a CA server using `cfssl serve` and then requesting client certs on remote nodes.
The client nodes need a copy of the root certificate (ca.pem) file generated on the CA server.

I can't find an easy way of retrieving this using the cfssl command or api. Am I missing something?

**Comment by kisom** [comment]
There's a `cfssl info` command; it takes `-remote` and `-profile` flags too. Similarly, the client package should let you access the info endpoint from Go programs. You can check that your server has the info endpoint working using

``` 
curl -d '{}' -X POST http://your.ca.net/api/v1/cfssl/info
```
 The [API docs](https://github.com/cloudflare/cfssl/blob/master/doc/api/endpoint_info.txt) should have some more info on this, too.

**Comment by chrisb3ll** [comment]
I was missing something! - thanks @kisom, this is working perfectly. 😄
