### ISSUE TITLE
Documentation confusing with 1.6 build instructions

### ISSUE THREAD

**Issue by diakula** [cloudflare/cfssl#686]
I see the following text in the readme:

> Note that CFSSL makes use of vendored packages; in Go 1.6, the GO15VENDOREXPERIMENT environment variable will need to be set, e.g.
>
> export GO15VENDOREXPERIMENT=1
> In Go 1.6, this works out of the box.

I suppose the first mentioning of Go 1.6 should read 1.5?

**Comment by JLofgren** [comment]
I'm also confused. Please clarify this.
