### ISSUE TITLE
ocsprefresh & ocspdump broken or misunderstood

### ISSUE THREAD

**Issue by aoe-mak** [cloudflare/cfssl#688]
Hey,

is it possible that ocsprefresh & ocspdump are broken?
[It is also possible that I don´t understand the proper workflow. ;)]

I set up a cert for ca.
I set up a cert for intermediate (signed by ca).
I set up a cert for ocsp (signed by intermediate).
I set up a cert for a webserver (signed by intermediate).

As far as I understand the description of the command ocsprefresh, it should fill the table ocsp_responses with the certificates from the table certificates. But it is empty.

Then I created an entry in the database with ocspsign. But the output of ocspdump is empty.
So I used the output from ocspsign to create a response list ocspserve.
With OCSP-stapling in the Webserver and Firefox as the client, the test for revoking a certificate signed by an intermediate was successful.

Here my commands:
`
# Create CA
cfssl gencert -initca ca.json -loglevel=0| cfssljson -bare ca -
# Create Intermediate
cfssl gencert -ca ca.pem -ca-key ca-key.pem -config=config-cfssl.json -profile=intermediate intermediate.json | cfssljson -bare intermediate -
# OCSP cert
cfssl gencert -ca intermediate.pem -ca-key intermediate-key.pem -config config-cfssl.json -profile=ocsp ocsp.json | cfssljson -bare ocsp -
# Start API server
screen -S api -t api
cfssl serve -address 127.0.0.1 -port 8888 -db-config=config-db.json -loglevel=0 -ca=intermediate.pem -ca-key=intermediate-key.pem -config=config-cfssl.json -responder=ocsp.pem -responder-key=ocsp-key.pem
# Create server key + csr
cfssl genkey -config=config-cfssl.json server.json | cfssljson -bare server
# Sign/Create demo certificate
cfssl sign -csr=server.csr -ca=intermediate.pem -ca-key=intermediate-key.pem -config=config-cfssl.json -profile=server -db-config=config-db.json | cfssljson -bare server
# Create OCSP database
cfssl ocspsign -ca intermediate.pem -responder ocsp.pem -responder-key ocsp-key.pem -cert server.pem | cfssljson -bare -stdout >> ocsp.db
# Start OCSP server
screen -S ocsp -t ocsp
cfssl ocspserve -address 127.0.0.1 -port 8889 -responses ocsp.db
# Revocation
openssl ocsp -issuer intermediate.pem -no_nonce -cert server.pem -CAfile intermediate.pem -text -url http://127.0.0.1:8889
cfssl ocspsign -db-config=db-pg.json -status=revoked -revoked-at=now -reason=4 -ca intermediate.pem -responder ocsp.pem -responder-key ocsp-key.pem -cert server.pem | cfssljson -bare -stdout >> ocsp.db
openssl ocsp -issuer intermediate.pem -no_nonce -cert server.pem -CAfile intermediate.pem -text -url http://127.0.0.1:8889
`

Cheers

**Comment by lziest** [comment]
can you dump the certificates table used by the API server? It's likely issued certificates are not stored in DB, so `ocsprefresh` and `ocspdump` does nothing.

**Comment by aoe-mak** [comment]
Surprisingly everything works. Magic hands and so on.

So, our proper workflow.

`cfssl gencert -initca cert_ca.json -loglevel=0 | cfssljson -bare cert_ca -
cfssl gencert -ca cert_ca.pem -ca-key cert_ca-key.pem -config=config-cfssl.json -profile=intermediate cert_intermediate.json | cfssljson -bare cert_intermediate -
cfssl gencert -ca cert_intermediate.pem -ca-key cert_intermediate-key.pem -config config-cfssl.json -profile=ocsp cert_ocsp.json | cfssljson -bare cert_ocsp -
screen -S api -t api
cfssl serve -address 0.0.0.0 -port 8888 -db-config=config-db.json -loglevel=0 -ca=cert_intermediate.pem -ca-key=cert_intermediate-key.pem -config=config-cfssl.json -responder=cert_ocsp.pem -responder-key=cert_ocsp-key.pem
cfssl genkey -config=config-cfssl.json cert_entity.json | cfssljson -bare cert_entity
cfssl sign -csr=cert_entity.csr -ca=cert_intermediate.pem -ca-key=cert_intermediate-key.pem -config=config-cfssl.json -profile=entity -db-config=config-db.json | cfssljson -bare cert_entity
cfssl revoke -db-config config-db.json -serial SERIAL -aki AKI -reason 4
cfssl ocsprefresh -db-config config-db.json -ca cert_intermediate.pem -responder cert_ocsp.pem -responder-key cert_ocsp-key.pem
cfssl ocspdump -db-config config-db.json > ocsp.db
cfssl cert_ocspserve -address 0.0.0.0 -port 8889 -responses cert_ocsp.db
openssl ocsp -issuer cert_intermediate.pem -no_nonce -cert cert_entity.pem -CAfile cert_intermediate.pem -text -url http://127.0.0.1:8889
`
