### ISSUE TITLE
Please review pkcs11key API change

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#696]
Hi cfssl folks,

I'm proposing a breaking API change for `pkcs11key` at https://github.com/letsencrypt/pkcs11key/pull/10. I think this will make for a much more usable package. Curious to get your feedback as users of the package.

Thanks,
Jacob

**Comment by lziest** [comment]
I do like the approach.

**Comment by jsha** [comment]
API change has landed, thanks for the input!
