### ISSUE TITLE
MySQL: Wrong size for serial number column

### ISSUE THREAD

**Issue by drf** [cloudflare/cfssl#703]
Currently, the MySQL backend is non-functional due to a very simple mistake in https://github.com/cloudflare/cfssl/blob/master/certdb/mysql/migrations/001_CreateCertificates.sql#L5 : the size of the serial_number field should be 128 instead of 20, as obviously apparent in https://github.com/cloudflare/cfssl/blob/437c6213e569dde639fd116272c27557fd38eaf9/scan/vendor/crypto/tls/generate_cert.go#L107

I'd do a PR myself, but I'm not sure whether I should update the existing migration or create one. Consider that as it stands today, the current DB is non-functional in terms of revocation.

Waiting for input.

**Comment by lziest** [comment]
You can change it directly. I prefer that way.
