### ISSUE TITLE
Make CFSSL extensible with respect to local signers

### ISSUE THREAD

**Issue by smithbk** [cloudflare/cfssl#711]
CFSSL should be extensible with respect to local signers to enable various HSM solutions to be plugged in.  This applies to both CSR signing as well as OCSP processing in which a private key is assumed to be accessible in memory, rather than in hardware as is the case for an HSM.

**Comment by smithbk** [comment]
Hi, any comments on this would be appreciated.  Thanks

**Comment by jsha** [comment]
Looks like this was resolved by #712 and can be closed.
