### ISSUE TITLE
API changes for OCSP responder

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#732]
Currently the OCSP responder uses this interface to allow user-defined data sources:

```
type Source interface {
	Response(*ocsp.Request) ([]byte, bool)
}
```

This has two problems:

 - Since it returns only a bool (`found`), it has no way to distinguish between "no response found" and "internal server error." For instance, a client that asks for OCSP for a non-existent serial should get an OCSP response indicating "unauthorized," and an HTTP 200 status. A database failure or timeout should result in HTTP 500 or 503.

 - There's not a good way to override HTTP headers. For instance, Let's Encrypt's OCSP responder is fronted by Akamai. The caching headers that responder.go provides are RFC 5019 compliant, and indicate that a response may be cached until its NextUpdate (effectively, until the response expires). That's correct behavior, but for our own edge cache we would like to send special Edge-Control headers that tell Akamai to re-fetch after 3 days instead of the 7 days indicated by the NextUpdate field in the response, because otherwise no one can actually retrieve the fresh responses when we generate them, because they older ones are still in the Akamai cache.

For the first problem, I suggest changing the Source interface to return an error instead of a bool, and to define a `NotFoundError` that implementations can return for not found. Any other error would be trigger an HTTP 5xx status code.

I'm not sure of the best way to solve the second problem. Thoughts welcome!

cc @rolandshoemaker @cpu

**Comment by cpu** [comment]
For the first, +1 on an error instead of bool. That seems more idiomatic overall. 

Would it be easier to introduce this as a second independent function in the `Source` interface rather than changing the original one to use `error`? The original could be implemented in terms of the new one with a `err != nil` and it might avoid the hassle of breaking the API. Any maintainers have thoughts?

For the second, I previously filed a ticket for the cache heading override as https://github.com/cloudflare/cfssl/issues/623 - I admit I forgot about it since then :-)

**Comment by jsha** [comment]
Note that my thinking has changed since #623. We'd actually like the end-user to receive a max-age that allows them to cache OCSP for the full lifetime of the response, but tell our CDN (in this case Akamai) that they should refresh earlier than that. We can use the Edge-Control header for that purpose, but it's probably too specific to put into the cfssl implementation. So we want some fairly generic method to set extra headers based on the OCSP response.

**Comment by rolandshoemaker** [comment]
We've agreed internally that the best path forward on this is to simply modify/extend the existing `Source` interface. This would remove the returned `bool` in favor of an `error` and add a third return value of `http.Header` which would be used to set extra headers if provided. A special `NotFound` error would be defined in the `ocsp` package to replace the `bool` found/not found functionality and any other error being returned would be treated as a 500.

cc @lziest @kisom does this seem acceptable to you? It's a breaking API change but should be a relatively easy update for anyone.
