### ISSUE TITLE
DB migration tool `goose` is currently broken due to a breaking change of sqlite driver.

### ISSUE THREAD

**Issue by lziest** [cloudflare/cfssl#741]
See https://bitbucket.org/liamstask/goose/pull-requests/58/lock-sqlite3-dependency-to-gopkgin-mattn/diff
and https://github.com/mattn/go-sqlite3/issues/394

**Comment by kisom** [comment]
I ended up building a tool based on [`migrate`](https://github.com/mattes/migrate/) for [cfssl-trust](https://github.com/cloudflare/cfssl_trust).

**Comment by mattn** [comment]
Sorry, I'll fix go-sqlite3.

**Comment by lziest** [comment]
@mattn don't worry we can figure this out, it is just a test util.

**Comment by lziest** [comment]
it's fixed. Thanks.
