### ISSUE TITLE
cfssl serve not reading certain JSON fields

### ISSUE THREAD

**Issue by mikesmitty** [cloudflare/cfssl#743]
It looks like some of the fields in the JSON config (address, db-config, and aki at least) are not being read from JSON. I can set the address and db-config flags from the command line, but that's a bit less than ideal. 

I also tried setting the aki field using the -aki flag, but it isn't getting inserted into the certificates.authority_key_identifier column in MySQL, preventing certificate revocation. I assume it's not being read from the config file, but it could be a separate issue altogether.

Edit: I should probably mention that this is compiled with go 1.8, the linux x86_64 package from golang.org/dl/

Here are my setup steps:
```
$ git clone https://github.com/cloudflare/cfssl.git $GOPATH/src/github.com/cloudflare/cfssl
$ cd $GOPATH/src/github.com/cloudflare/cfssl/
$ pushd cli/serve && rice embed-go && popd
$ go get github.com/cloudflare/cfssl/cmd/cfssl
$ go get github.com/cloudflare/cfssl/cmd/...
$ cfssl serve -ca ca.pem -ca-key ca-key.pem -config config.json
2017/03/29 14:40:45 [INFO] Initializing signer
2017/03/29 14:40:45 [WARNING] couldn't initialize ocsp signer: open : no such file or directory
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/gencrl' is enabled
2017/03/29 14:40:45 [WARNING] endpoint 'ocspsign' is disabled: signer not initialized
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/init_ca' is enabled
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/certinfo' is enabled
2017/03/29 14:40:45 [WARNING] endpoint 'revoke' is disabled: cert db not configured (missing -db-config)
2017/03/29 14:40:45 [INFO] endpoint '/' is enabled
2017/03/29 14:40:45 [INFO] setting up key / CSR generator
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/newkey' is enabled
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/scan' is enabled
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/scaninfo' is enabled
2017/03/29 14:40:45 [WARNING] endpoint 'sign' is disabled: {"code":5200,"message":"Invalid or unknown policy"}
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/info' is enabled
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/newcert' is enabled
2017/03/29 14:40:45 [INFO] bundler API ready
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/bundle' is enabled
2017/03/29 14:40:45 [INFO] endpoint '/api/v1/cfssl/authsign' is enabled
2017/03/29 14:40:45 [WARNING] endpoint 'crl' is disabled: cert db not configured (missing -db-config)
2017/03/29 14:40:45 [INFO] Handler set up complete.
2017/03/29 14:40:45 [INFO] Now listening on 127.0.0.1:8888
```

This is the config I'm using:
```
{
    "address": "10.x.x.x",
    "cafile": "/etc/cfssl/ca.pem",
    "cakeyfile": "/etc/cfssl/ca-key.pem",
    "tls-cert": "<removed>",
    "tls-key": "<removed>",
    "responder": "<removed>",
    "responder-key": "<removed>",
    "aki": "<removed>",
    "db-config": "/etc/cfssl/db-config.json",
    "signing": {
	"profiles": {
            "server": {
                "auth_key": "key1",
                "expiry": "8760h",
                "usages": [
                    "signing",
                    "key encipherment",
                    "server auth"
                ]
            },
            "client": {
                "auth_key": "key1",
                "expiry": "8760h",
                "usages": [
                    "signing",
                    "key encipherment",
                    "client auth"
                ]
            }
        },
        "default": {
            "auth_key": "key1",
            "expiry": "8760h",
            "usages": [
                "signing",
                "key encipherment",
                "client auth",
                "server auth"
            ]
        }
    },
    "auth_keys": {
        "key1": {
            "type": "standard",
            "key": "<removed>"
        }
    }
}
```

**Comment by lziest** [comment]
yes, not all cli parameters have corresponding equivalent conf key in the conf.json. We will need to update the documentation to reflect that. The conf.json were mainly used for setup a CA signer, for how a certificate should be issued. And the db conf you want to use is not there, please raise this as a feature request. Since you can refer the conf object is being define https://github.com/cloudflare/cfssl/blob/master/config/config.go#L512

**Comment by mikesmitty** [comment]
Ah, ok. Thanks for the info. The only critical issue I have is regarding setting the aki. It doesn't appear to work from the cli or from the config. I'm assuming it should show up in the certificates table after generating a cert? The column is empty even when specifying aki on the command line with mysql.

**Comment by lziest** [comment]
The aki should be automatically generated through x509.CreateCertificate. Unless Go 1.8 changes the implementation of its standard API. See here https://github.com/cloudflare/cfssl/blob/master/signer/local/local.go#L397
See my comments embedded there.

With a cursory look, it does appear that AKI is not longer automatically encoded.

**Comment by mikesmitty** [comment]
Oh, ok. So cfssl pulls it from the cert automatically? That would make things simpler. Yeah, I had heard that some recent version of Go stopped adding the aki automatically. Thanks for the info.

**Comment by lziest** [comment]
after looking harder, I think AKI should be set up automatically if the signing CA has subject key id.

**Comment by lziest** [comment]
@mikesmitty do you manage to get AKI set?

**Comment by mikesmitty** [comment]
I'm having some issues with gencert falling back to /sign instead of /authsign so I can't test right now, but looking back at the ca cert I was using did actually have the Subject Key Identifier field set while I was testing previously and it wasn't setting the aki in the database.

```
openssl x509 -in ca.pem.bak -noout -text |grep -A1 'Key Identifier'
            X509v3 Subject Key Identifier:
                CA:64:2D:82:05:CE:46:62:8B:B0:28:33:91:D3:AD:2E:64:D5:57:39
```

**Comment by mikesmitty** [comment]
Ok, figured out what I was doing wrong with gencert. Still no luck with the new ca cert either.  This is the json I'm using to generate the CA cert:

```
{
    "hosts": [
        "<removed>"
    ],
    "key": {
        "algo": "ecdsa",
        "size": 256
    },
    "names": [
        {
            "C": "US",
            "L": "<removed>",
            "O": "<removed>",
            "OU": "<removed>",
            "ST": "<removed>"
        }
    ]
}
```

**Comment by lziest** [comment]
I will try to debug this at this weekend.

**Comment by mikesmitty** [comment]
Thanks for looking into it, I appreciate it.

**Comment by mikesmitty** [comment]
Ok, so I did some digging into this and figured out the cause. I was leaving off the CN field in both the CA and the client certificates, making the DN (and the whole Certificate.Subject field) identical, which triggered the self-signed cert SKI/AKI logic in crypto/x509:
https://github.com/golang/go/blob/release-branch.go1.8/src/crypto/x509/x509.go#L1753

I would think that the check for self-signed certs would be based off the keypair rather than the certificate subject, but I guess whoever added that check never expected someone like me to accidentally leave off the CN.

**Comment by lziest** [comment]
Indeed, maybe you can raise it to Go Devs, I think they are pretty responsive.
