### ISSUE TITLE
Installing with Brew

### ISSUE THREAD

**Issue by talktopri** [cloudflare/cfssl#752]
Would `brew install cfssl` work?

**Comment by billchurch** [comment]
Assuredly so! Tested on Yosemite.

![screenshot 2017-04-19 07 37 14](https://cloud.githubusercontent.com/assets/1668075/25178184/bf594ef4-24d2-11e7-96b1-18bfce4cd60b.png)

**Comment by talktopri** [comment]
Thanks @billchurch!
