### ISSUE TITLE
cfssl sqlite db schema is not working properly (bytea should be blob)

### ISSUE THREAD

**Issue by sigsegv11** [cloudflare/cfssl#759]
When using the sqlite schema the bytea type is not recognized correctly causing the type to be dynamically stored.
One nasty side effect is that the serial number is stored as a number which makes generation of a (working) CRL using the sqlite database impossible.

**Comment by lziest** [comment]
can you provide a PR fixing it?

**Comment by sigsegv11** [comment]
after a long wait: done
