### ISSUE TITLE
question: Documentation

### ISSUE THREAD

**Issue by zer09** [cloudflare/cfssl#761]
Hello good day,

I just wanna ask where  I can find the documentation for the keys on the json file.
eg.
```
{
    "hosts": [
        "example.com",
        "www.example.com"
    ],
    "key": {
        "algo": "rsa",
        "size": 2048
    },
    "names": [
        {
            "C": "US",
            "L": "San Francisco",
            "O": "Internet Widgets, Inc.",
            "OU": "WWW",
            "ST": "California"
        }
    ]
}
```

what is the meaning of the "OU", "ST", etc and what is their use/purpose for the certificate?
sorry, I tried to google it but I cant find any.

Thanks

**Comment by lziest** [comment]
the key is specified with "key" object, which should be straightforward to understand. The names are certificate subject DN, this may help you understand: http://stackoverflow.com/questions/6464129/certificate-subject-x-509
