### ISSUE TITLE
Renew the certificate without key regeneration

### ISSUE THREAD

**Issue by kayrus** [cloudflare/cfssl#762]
I have a key, certificate and json file which was used for this certificated. Certificate has expired and now I'm trying to create a new CSR.

Here is the command which I use:

```
$ cfssl sign -ca ca.pem -ca-key ca-key.pem -profile server -config profiles.json server.pem
{"code":9300,"message":"not a certificate or csr"}
```

According to its output it is possible to provide old certificate, but it doesn't recognize the `server.pem`. Also I don't know hot to generate a new CSR using json file without regenerating the private key. I know how to do this using openssl, but how can I do this within cfssl?

**Comment by lziest** [comment]
yes, you need to sign a csr. We will update the bad error messages. It's not hard to generate a csr if you have the private key.

**Comment by lziest** [comment]
the beef of generate csr from private key and a csr json object is actually ready. I can make a cli tool for csr generation with a existing private key, but if you are in a hurry, you can use
https://github.com/cloudflare/cfssl/blob/master/csr/csr.go#L365

**Comment by kayrus** [comment]
Ideally it would be great to generate CSR from the existing old certificate.

**Comment by lziest** [comment]
you can do that too, https://godoc.org/github.com/cloudflare/cfssl/csr#ExtractCertificateRequest

**Comment by lziest** [comment]
I think #764 can do what your want @kayrus. Closing.
