### ISSUE TITLE
question: how can setup the config to include extended key usage?

### ISSUE THREAD

**Issue by zer09** [cloudflare/cfssl#766]
Hello good day,

I cant find any documentation on how to include extension key usage, on the json config .
Because I want to add ExtKeyUsageServerAuth. 

How can i specify it on the config file?

thanks.

**Comment by lziest** [comment]
pretty straightforward, specify it in the usages:
https://github.com/cloudflare/cfssl/blob/master/doc/cmd/cfssl.txt#L170
For all supported values, see https://github.com/cloudflare/cfssl/blob/master/config/config.go#L568
PR is welcomed.
