### ISSUE TITLE
cfssljson can't parse sign API response with bundle option enabled

### ISSUE THREAD

**Issue by miccrun** [cloudflare/cfssl#769]
I set up a API server using cfssl serve, with --ca-bundle and --int-bundle.
Then I curl /api/v1/cfssl/sign with bundle option is true, and pipe the response to cfssljson, got an error like:

>panic: interface conversion: interface is map[string]interface {}, not string
goroutine 1 [running]:
panic(0x51e3c0, 0xc8200442c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.main()
	/go/src/github.com/cloudflare/cfssl/cmd/cfssljson/cfssljson.go:152 +0xdab

```
{
    "errors": [],
    "messages": [],
    "result": {
        "bundle": {
            "bundle": "-----BEGIN CERTIFICATE-----...",
        ...
        },
        "certificate": "-----BEGIN CERTIFICATE-----..."
    },
    "success": true
}
```

Above was the API response, I think cfssljson expects the value of `bundle` to be a string, but actually it's a JSON object with another `bundle` key nested.

**Comment by lziest** [comment]
you are right, the bundle object in API sign response is not conformed with original `cfssljson` assumption. Would you make a PR to `cfssljson` to take this outlier use case in?

**Comment by Feld0** [comment]
@lziest See #796 - I needed this as well and fixed it in a PR.
