### ISSUE TITLE
-bash: cfssl: command not found

### ISSUE THREAD

**Issue by juzhao** [cloudflare/cfssl#774]
Installed go 1.8.3 and  installed cfssl via "go install github.com/cloudflare/cfssl/cmd/cfssl", 
when use cfssl to create cert, error thrown out "cfssl: command not found"

**Comment by lziest** [comment]
use `cfssl -h` to find command.

**Comment by manesioz** [comment]
I am receiving the same error after running `go get -u github.com/cloudflare/cfssl/cmd/...` 
My go version is `1.13.7` so it shouldn't be an issue with that (requires `1.12+`) 
Any ideas?

**Comment by Alexcornila** [comment]
why was this closed without a proper resolution? If this tool is not supported any longer please remove

**Comment by linhil** [comment]
does it is installed with bin file will work? 
see https://www.cnblogs.com/stonecode/p/12502399.html
