### ISSUE TITLE
Release anytime soon?

### ISSUE THREAD

**Issue by jason-riddle** [cloudflare/cfssl#782]
There hasn't been a release since Mar 2016 and there have been a lot of commits since then. Will there be a release of the binary anytime soon?

**Comment by jason-riddle** [comment]
Bumping incase this issue wasn't noticed.

**Comment by 030** [comment]
+1

**Comment by bkleef** [comment]
+1

**Comment by bradjonesca** [comment]
+1

**Comment by patrickf55places** [comment]
Pinging @kisom and @lziest to hopefully get their attention on this.

**Comment by cbroglie** [comment]
Some good news here: https://github.com/cloudflare/cfssl/issues/995#issuecomment-548473012. Follow #995 for additional updates.
