### ISSUE TITLE
mkbundle concats certificates in arbitrary order, not RFC5246 conform

### ISSUE THREAD

**Issue by zwopir** [cloudflare/cfssl#790]
Hi, 

thanks for the awesome tool!
If I understand https://tools.ietf.org/html/rfc5246#section-7.4.2 correctly, certificates in a bundle have to be in a specific order. However `mkbundle` parses the certificates in separate goroutines and then writes them to the file in the order they are passed to the channel.

I would expect that the certificates are written to the output file in the order they are listed in the command line arguments.

As a workaround setting the number of workers to one works for me.

**Comment by lziest** [comment]
the word 'bundle' is overloaded. At the RFC occasion, it's about a certificate chain, that must form a trust chain. At some other occasion, it simply means a bunch certificates put together. So `mkbundle` is not for your use case, `cfssl bundle` is.

**Comment by zwopir** [comment]
Hi Zi Lin,

thanks for the reply and the clarification!

**Comment by gautaz** [comment]
Just for the next readers, I have tried a bit the bundle API and the result  is available here:
https://github.com/gautaz/docker-alpine-cfssl#intermediate-ca

I hope this is accurate and will help.
