### ISSUE TITLE
Storing AKI in CertDB fails with Go 1.9

### ISSUE THREAD

**Issue by mastersingh24** [cloudflare/cfssl#801]
cfssl passes an X509 certificate template [here ](https://github.com/cloudflare/cfssl/blob/master/signer/local/local.go#L385)and then assumes that X509.CreateCertificate will fill in the AKI in the template and sets the AKI with this assumption [here ](https://github.com/cloudflare/cfssl/blob/master/signer/local/local.go#L395)

Unfortunately, Go 1.9 no longer fills in the AKI in the template passed to X509.CreateCertificate.  You can see that [here ](https://golang.org/src/crypto/x509/x509.go?s=19833:23432#L1786)

A proposed fix for this would be to parse the signed cert bytes which are returned and extract the AKI from the signed certificate rather than the template passed in

**Comment by lziest** [comment]
thanks for reporting. I think I saw those lines of code prior to 1.9 (unless you are referring a different piece of code)
```
    authorityKeyId := template.AuthorityKeyId
    if !bytes.Equal(asn1Issuer, asn1Subject) && len(parent.SubjectKeyId) > 0 {
        authorityKeyId = parent.SubjectKeyId
    }
```


So my understanding is that:
AKI is still populated when the the cert to-be-signed is not self-signed, and the signer CA cert has Subject Key Id, then CA's subject key id is the certTBS's AKI.

**Comment by mastersingh24** [comment]
Right - so the cert is signed and has the right AKI.  The problem is that the AKI does not get stored in CertDB (if you are using CertDB).

        var signedCert []byte
	signedCert, err = s.sign(&certTBS, profile)
	if err != nil {
		return nil, err
	}

	if s.dbAccessor != nil {
		var certRecord = certdb.CertificateRecord{
			Serial: certTBS.SerialNumber.String(),
			// this relies on the specific behavior of x509.CreateCertificate
			// which updates certTBS AuthorityKeyId from the signer's SubjectKeyId
			AKI:     hex.EncodeToString(certTBS.AuthorityKeyId),
			CALabel: req.Label,
			Status:  "good",
			Expiry:  certTBS.NotAfter,
			PEM:     string(signedCert),
		}

		err = s.dbAccessor.InsertCertificate(certRecord)
		if err != nil {
			return nil, err
		}
		log.Debug("saved certificate with serial number ", certTBS.SerialNumber)
	}

**Comment by mastersingh24** [comment]
I'm happy to submit an attempt at a fix?

**Comment by lziest** [comment]
sure, PR is appreciated.

**Comment by lziest** [comment]
I got it, so tbsCert has empty AKI, only signedCert has good AKI, right?

**Comment by mastersingh24** [comment]
correct

**Comment by mastersingh24** [comment]
I'll submit a PR shortly
