### ISSUE TITLE
Add instructions for installing cfssl with docker

### ISSUE THREAD

**Issue by jamiehannaford** [cloudflare/cfssl#810]
Would it be possible to add installation instructions for folks who don't want to (or can't) install go dependencies on their host? This could be done in a one-liner with docker:

```bash
$ docker run --rm -v /usr/local/bin:/go/bin golang go get -u github.com/cloudflare/cfssl/cmd/cfssl
```

If the maintainers are okay with this I can send a PR.

**Comment by JasonGiedymin** [comment]
FYI there is a provided image if you don’t want to track master  https://hub.docker.com/r/cfssl/cfssl/
