### ISSUE TITLE
Support for the E (email) tag

### ISSUE THREAD

**Issue by Narev** [cloudflare/cfssl#826]
It seems that when you generate a certifcate with an E tag/attribute in the csr it is omitted. The same goes for if you generate your own csr that contains an E tag the generated certificate will not copy the email tag. Would it be possible to include this tag?

**Comment by Narev** [comment]
No i switched to generating my certificates manually using keystore
explorer.

Op di 7 aug. 2018 17:24 schreef Unb9rn <notifications@github.com>:

**Comment by cubicrace** [comment]
Do we have a date on when this could be fixed ? Microsoft / Jamf SCEP profiles allow to add the E attribute certificate subjects and this could break thinks for a lot of customers

**Comment by aklyachkin** [comment]
The origin of the problem seems to be here - https://golang.org/pkg/crypto/x509/pkix/#Name
There is no field for e-mail in the standard Go library
