### ISSUE TITLE
How to obtain initial CA passed from cli via API call

### ISSUE THREAD

**Issue by f0o** [cloudflare/cfssl#856]
Hi,

we have `ca.pem` and `ca-key.pem` in `/etc/cfssl` and them just run `cfssl serve`.

How do we obtain this CA via the API?

The Bundle-Endpoint seems to only deal with external resources. Or I fail to see how to request the internal CA via it.

Thanks!

**Comment by kisom** [comment]
There's the /api/v1/cfssl/info endpoint (e.g. via the `cfssl info` command). Is that what you're looking for?

**Comment by f0o** [comment]
That endpoint requires a parameter and no matter what I send it, I get a 404 :/

**Comment by kisom** [comment]
Does this work?

```
curl -X POST --data-binary '{}' http://127.0.0.1:8888/api/v1/cfssl/info
```

**Comment by f0o** [comment]
```
~ $ curl -X POST --data-binary '{}' http://127.0.0.1:8888/api/v1/cfssl/info
404 page not found
```

:/

**Comment by f0o** [comment]
Ok this was unfortunately - Turns out there was a timing issue in the systemd files which lead to cfssl.service not waiting for the CA-cert to be fully generated.

the mentioned curl call works as expected. Thanks @kisom :)
