### ISSUE TITLE
Add travis check for go 1.6/1.7 or increase requirement

### ISSUE THREAD

**Issue by dol** [cloudflare/cfssl#866]
When building the cfssl with go 1.7 it fails with the following error message

```
$ go get -u github.com/cloudflare/cfssl/cmd/cfssl
../.gvm/pkgsets/go1.7/global/src/github.com/cloudflare/cfssl/vendor/github.com/google/certificate-transparency-go/jsonclient/backoff.go:45: undefined: time.Until
../.gvm/pkgsets/go1.7/global/src/github.com/cloudflare/cfssl/vendor/github.com/google/certificate-transparency-go/jsonclient/client.go:230: undefined: time.Until
```

This is due to the introduction of `time.Until` in go 1.8. The README.md states that version 1.6+ is required => https://github.com/cloudflare/cfssl/blame/master/README.md#L11

**Comment by martinszy** [comment]
Same error here, please update documentation, I lost one hour fiddling with things.

**Comment by cbroglie** [comment]
Sorry about the confusion, the README has been updated to reflect the Go 1.8+ requirement.
