### ISSUE TITLE
Add the possibility to issue Origin / Cloudflare signed certificates

### ISSUE THREAD

**Issue by RektibouCaribou** [cloudflare/cfssl#869]
Hi,

The other day I was wondering if it was a possibility to use CFSSL as a means to issue an Origin Certificate from Cloudflare, after having contacted the support about this, they told me it was not possible to do this, yet. 

They told me to post an issue here, which I honestly should've thought about it before.

So, what do you guys think about adding the possibility to issue Cloudflare signed certificates with the CFSSL tool?

**Comment by kisom** [comment]
Hello @RektibouCaribou, cfssl doesn't contain really any Cloudflare-specific parts. If we were to release a tool for issuing origin certificates, it'd be a separate, standalone tool.
