### ISSUE TITLE
CN/Common Name Not being included in CSR/Certificate with gencert

### ISSUE THREAD

**Issue by cacsar** [cloudflare/cfssl#884]
I'm testing out cfssl for the first time and it looks as though common name/CN isn't getting through to the CSR (or certificate) when using gencert, but does get through to the certificate when using a CSR generated with openssl. I didn't find anything from searching through the documentation to suggest that this was expected behavior, but if I missed something (such as some configuration), please do let me know.
cfssl version gives
```Version: 1.3.2
Revision: dev
Runtime: go1.10
```

It doesn't look like the same sort of root issue as in #632, as "CN" does still seem to be in the go PKIX library's list of things it knows about (assuming https://golang.org/src/crypto/x509/pkix/pkix.go is correct). I haven't tried with other versions of Go yet, I was using Go 1.10 to avoid #824.

The simplest test JSON I tried was
```{
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names" : [
    {
      "CN":"Test Common Name",
      "OU":"84d89861-6e79-42ec-acc7-bae9d719b02b",
      "O":"1012be7a-5a0a-403a-9210-576b6dd5a933"
    }
  ]
}```

My intent was to issue client certificates for use with specific servers running software Ican change, so I have leeway on which fields I use for which purpose.

**Comment by lziest** [comment]
I remember "CN" is special, you can specify it in isolation.

Try {
...,
"CN": "test",
names : [ {...}]
}

**Comment by cacsar** [comment]
Yep that's totally in the main readme, and that took care of it.
