### ISSUE TITLE
Install failed on macOS 10.14 and go 1.10.3

### ISSUE THREAD

**Issue by idealhack** [cloudflare/cfssl#899]
```bash
go get -u github.com/cloudflare/cfssl/cmd/cfssl                                                                                                                                                            
# github.com/cloudflare/cfssl/cmd/cfssl
/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64/link: /usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)
```

same errors with other commands

**Comment by HeminWon** [comment]
me too

**Comment by adamdecaf** [comment]
Could this be https://github.com/golang/go/issues/25908 ?

**Comment by qiyongxiao** [comment]
make etcd project, it's appeared

**Comment by ricketybridge** [comment]
> make etcd project, it's appeared

What does this mean?

**Comment by adamdecaf** [comment]
@idealhack @HeminWon @qiyongxiao could you try on go 1.11 beta? 

https://groups.google.com/forum/#!msg/golang-nuts/vpVOVVMLa08/oQQQWX3rCgAJ

**Comment by ricketybridge** [comment]
@adamdecaf I just tried the cfssl installation with go 1.11 beta and came here to post that I'm no longer getting the error this issue refers to.

**Comment by adamdecaf** [comment]
Cool. It looks like the fix is being backported to 1.10 also https://github.com/golang/go/issues/25912, so I'd expect a 1.10 release within a week or two fixing this.

**Comment by idealhack** [comment]
Yeah, I'll try again after Go 1.10.4 released this weekend.

**Comment by qiyongxiao** [comment]
@adamdecaf not yet

**Comment by cmendesce** [comment]
I used the go version `1.11beta1` and it works for me. 
Try  `go1.11beta1 get -u github.com/cloudflare/cfssl/cmd/...`

**Comment by idealhack** [comment]
Now with Go 1.11 and 1.10.4 released, I believe this can be closed.

Feel free to reopen if it still relevant.
