### ISSUE TITLE
Build error: SQLiteConn

### ISSUE THREAD

**Issue by ricketybridge** [cloudflare/cfssl#903]
Building this for darwin/amd64 gives me this error:

```
-->      darwin/amd64: github.com/cloudflare/cfssl/cmd/mkbundle

1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/cloudflare/cfssl/vendor/github.com/mattn/go-sqlite3
vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:18:10: undefined: SQLiteConn
```

My machine has sqlite3 installed. 

EDIT:

Per the instructions [here](https://github.com/cloudflare/cfssl/tree/master/vendor/github.com/mattn/go-sqlite3), I ran `go install github.com/mattn/go-sqlite3`. No dice.

Also, my `go env` has `CGO_ENABLED="1"`.

Isn't mkbundle an optional feature anyway? It'd be great to be able to opt out of building it.

**Comment by cceckman** [comment]
Also seeing this when doing a crossbuild- from amd64 Linux to arm7, using go 1.10 or go 1.9.

Given the path refers to 1.8, maybe `cfssl` needs an update to the vendored lib?

**Comment by cbroglie** [comment]
Cross builds do not work out of the box with cgo applications. You'll need a compiler toolchain for each target.
