### ISSUE TITLE
Flag for min version of TLS for cli/serve

### ISSUE THREAD

**Issue by endform** [cloudflare/cfssl#912]
We run CFSSL as a server in an environment where we need to meet policy guidelines around the min version of TLS. I can add a flag "MinTLSVersion" and do some string mapping to the constants needed to pass into tls.Config, but would like to start a conversation on how to implement this in a way that will make the maintainers happy as I have not contributed to this project before.

**Comment by cbroglie** [comment]
Adding a new flag to `cli.Config`, and setting the `tls.Config.MinVersion` based on it sounds like a fine approach.

**Comment by endform** [comment]
@cbroglie would love it if you got a chance to review the #913, I'm open to any changes. I went back and forth about how to represent the versions as args, but should probably just change it to use 1.1 & 1.2. The other consideration I should address is how this will change when go's underlying default gets changed.

**Comment by cbroglie** [comment]
Fixed in #913
