### ISSUE TITLE
Adding support for URI SANs

### ISSUE THREAD

**Issue by jacobcase** [cloudflare/cfssl#921]
RFC 5280 specifies support for URI SANs along with the existing supported types (DNS, IP, Email). Unfortunately Go did not make this easy until the 1.10 release.  It is still possible to support it in a backwards compatible way by marshaling the asn1 data manually.

I would like to add support for this feature to CFSSL and submit a PR. Before I do, I want to make sure it is work that would be accepted, and that I implement it in a way everyone is happy with. That leaves me with a few questions.

1) Is this an acceptable addition to cfssl?
2) Should it still fall under `hosts` in the CSR JSON?
3) Should it still be compatible with go 1.8, is it unreasonable to require go 1.10?

Example URI fields:
`https://cfssl.org/`
`urn:some:resource`

Thank you for any feedback.

RFC: https://tools.ietf.org/html/rfc5280#section-4.2.1.6

**Comment by vjanelle** [comment]
Took a stab at this, but someone from cloudflare will have to make a decision about removing older versions of golang from the travis tests.

**Comment by cbroglie** [comment]
Fixed by #957
