### ISSUE TITLE
Support go modules

### ISSUE THREAD

**Issue by ogimenezb** [cloudflare/cfssl#932]
We should make it compatible with new modules.

Probably delete vendor folders #925?

**Comment by yesmar** [comment]
`make` works fine for me outside of `GOPATH` (which I don't use anymore) if I run `go mod init github.com/cloudflare/cfssl` from within the cfssl root. Seems to me you could just do that, commit `go.mod` and `go.sum`, and call it a day. I'm using go 1.13.1 if that matters.

**Comment by cbroglie** [comment]
Fixed in #1047
