### ISSUE TITLE
update executables on https://pkg.cfssl.org/

### ISSUE THREAD

**Issue by ketzacoatl** [cloudflare/cfssl#948]
Unless I am mistaken, it seems the latest release available in the github repo is 1.3.x, while the executable download page (https://pkg.cfssl.org/) has 1.2. Should users expect to find 1.3.x on https://pkg.cfssl.org/?

**Comment by asgoel** [comment]
Is this possible?

**Comment by cbroglie** [comment]
Some good news here: https://github.com/cloudflare/cfssl/issues/995#issuecomment-548473012. Follow #995 for additional updates.
