### ISSUE TITLE
Add support for PKCS#7 in bundle

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/cfssl#97]
Incoming certificates in PKCS#7 format (starting with "-----BEGIN PKCS7-----") should be supported in bundle. If the input PKCS#7 file contains a list of certificates, treat them as an incoming certificate chain.

The certificate and output chain should still be presented as PEM for the output.

Here's some discussion on the topic:
http://security.stackexchange.com/questions/73156/whats-the-difference-between-x-509-and-pkcs7-certificate

**Comment by ZenGround0** [comment]
I have been working on this issue.

**Comment by lziest** [comment]
This issue is fixed by #140
