### ISSUE TITLE
Lookup certificate by serial number

### ISSUE THREAD

**Issue by bombsimon** [cloudflare/cfssl#982]
Thanks for a great product!

In the setup we're using we are issuing short lived certificates to use for signing within the system. To verify the signature we're passing the serial number (and authority key id) since we, for several reasons, don't want to send the full certificate (or certificate chain). We then want to leave it up to the receiving party to fetch the certificate from CFSSL for verification.

I was a bit surprised that even though all the issued certificates and revocations are stored in the accessor database there was no API endpoint/CLI exposing the `GetCertificate()` function from the accessor interface.

Since I think it's a quite common usage to fetch the certificate based on the serial number I think it's reasonable to add support for it via the API and CLI.

I did a proposal of the implementation and will submit a PR shortly.

**Comment by bombsimon** [comment]
@cbroglie Not trying to rush anything but would love to hear if you even think this is reasonable at all? No need to stress but would be nice to know if it's plausible this kind of feature will be supported in a somewhat near future.

Thanks!

**Comment by bombsimon** [comment]
@cbroglie Thank you for commenting on and merging the PR! 🎉

What's the best way to get these changes into the official docker image? As far as I can tell it hasn't been updated within the last five months. I also noticed that the `Dockerfile` builds from go 1.9 which won't work. Should I make a PR with an updated docker image based on go 1.12? If so, do do you think you will update the official image or is it better if I build my own?

Thanks again!

**Comment by cbroglie** [comment]
I updated the Dockerfiles and have tagged a new 1.3.3 release. We'll work on updating the dockerhub images when we have some more spare cycles; in the meantime you should build your own image from our Dockerfile if you're blocked.
