### ISSUE TITLE
Travis build currently erroring

### ISSUE THREAD

**Issue by jsha** [cloudflare/cfssl#989]
It looks like the Travis build is currently erroring with this output:

```
/home/travis/.gimme/versions/go1.11.8.linux.amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-377698855/000024.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
https://travis-ci.org/cloudflare/cfssl/jobs/517594147

**Comment by cbroglie** [comment]
I believe that was due to https://github.com/golang/go/issues/31293 (it affected Go 1.11 and 1.12), which should be fixed. But it looks like tests are broken in master for all versions due to a different breakage currently.
