### ISSUE TITLE
Add support for multiple hostnames in the sign CLI and API

### ISSUE THREAD

**Issue by grittygrease** [cloudflare/cfssl#99]
Right now, the CLI for sign takes the hostname as a parameter or as a flag (-hostname). In the csr.CertificateRequest, cfssl accepts multiple hostnames, it should also do so if provided as the hostname.

The hostname parameter should be augmented to accept a comma-separated list of hostnames/IPs. This will allow the creation of multiple-SAN certs from the command line.

**Comment by dr107** [comment]
I'm thinking since I just got done adding unit tests to signer, it might be a good idea for me to try and tackle this feature. Does that sound like a good idea?

**Comment by grittygrease** [comment]
Great idea. This feature will be useful right away.

**Comment by dr107** [comment]
This issue should be resolved now that PR 118 has been merged.
