### ISSUE TITLE
Update docker repository

### ISSUE THREAD

**Issue by tomposmiko** [cloudflare/cfssl#999]
Can you please update the docker repository with the latest release? Github release tagged at 1.3.3, docker repository is at 1.3.2 only.

**Comment by Danpiel** [comment]
Also add `cfssl:minimal` prebuilt from Dockerfile.minimal, that would be awesome.

**Comment by SerialVelocity** [comment]
@cbroglie @cpu The docker repo is really out of date now (10 months).
Is it possible to either get docker auto-publishing again (latest and per version), or add something like:
#### This docker image is deprecated. Please use `alpine:edge` and run `apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing cfssl`

**Comment by cpu** [comment]
@SerialVelocity Sorry, I'm not a maintainer of this project and have the same access to the project and associated Docker repos as you do.

**Comment by SerialVelocity** [comment]
Ah, sorry about that. I read the commit history wrong! @cbroglie are you able to do it?
It's this repo:
https://hub.docker.com/r/cfssl/cfssl

**Comment by johanbrandhorst** [comment]
Bump. Need 1.4.0 released please.

**Comment by NerdsvilleCEO** [comment]
This probably isn't terribly helpful, but who knows... I implemented autobuild on a fork using the dockerfiles they provide

https://hub.docker.com/repository/docker/omnidapps/cfssl

**Comment by rustycl0ck** [comment]
Seems like the docker image is available under the Github Packages section - https://github.com/cloudflare/cfssl/packages/155902. 

But the problem with this is that you can't `docker pull` without authentication - https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358/12

**Comment by jinliming2** [comment]
I cannot `docker pull` from Github packages even I created an access token and logged in `docker login https://docker.pkg.github.com`.

Got this:
```bash
$ docker pull docker.pkg.github.com/cloudflare/cfssl/cfssl:1.4.1
Error response from daemon: Get "https://docker.pkg.github.com/v2/cloudflare/cfssl/cfssl/manifests/1.4.1": no basic auth credentials

$ docker login https://docker.pkg.github.com
Username: <My Email>
Password: <My Access Token>
Login Succeeded

$ docker pull docker.pkg.github.com/cloudflare/cfssl/cfssl:1.4.1
1.4.1: Pulling from cloudflare/cfssl/cfssl
c7b7d16361e0: Pulling fs layer
b7a128769df1: Pulling fs layer
1128949d0793: Pulling fs layer
667692510b70: Waiting
c70d80036479: Waiting
f332e1ccc3d8: Waiting
07e0a3e01633: Waiting
a83d971b0ddd: Waiting
6ea32dc08cc5: Waiting
d5b34c61a78b: Waiting
error pulling image configuration: denied: Encountered a billing-related error. Please verify the billing status for this account.
```

**Comment by arichtman** [comment]
Yea I'm getting the billing-related error too on pull with login succeeded using personal access token. I made sure my account had a valid credit card and set a spending limit for GitHub packages too...

**Comment by nickysemenza** [comment]
Sorry for the super long delay in response here folks, we've resuscitated our usage of Docker Hub, and I've pushed all of the missing versions (`1.3.3` through `1.5.0`) there: https://hub.docker.com/r/cfssl/cfssl/tags. 

Please use those in favor of the GitHub registry, new versions will be published to Docker Hub when new releases on GitHub are created going forward.
